# Import Libraries

In [1]:
#import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

In [2]:
#To print multiple outputs together
from __future__ import print_function

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#Change column display number during print
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)
pd.set_option('display.max_colwidth',-1)

import warnings
warnings.filterwarnings("ignore")

<ipython-input-2-e6aed52bba95>:10: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth',-1)

# Loading datasets

In [3]:
cust_df = pd.read_excel('../data/Customer_Data.xlsx')

In [4]:
inv_df = pd.read_csv('../data/Final_invoice.csv')

In [5]:
jtd_df = pd.read_csv('../data/JTD.csv')

In [6]:
plant_df = pd.read_excel('../data/PlantMaster.xlsx')

In [7]:
cust_df.info()
cust_df.shape
cust_df.isnull().sum()

inv_df.info()
inv_df.shape
inv_df.isnull().sum()

jtd_df.info()
jtd_df.shape
jtd_df.isnull().sum()

plant_df.info()
plant_df.shape
plant_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555338 entries, 0 to 555337
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Business Partner  555338 non-null  object
 1   Customer No.      555338 non-null  object
 2   Partner Type      555260 non-null  float64
 3   Data Origin       555202 non-null  object
 4   Title             509031 non-null  float64
 5   Marital Status    16037 non-null   float64
 6   Occupation        14558 non-null   float64
 7   Date of Birth     13444 non-null   object
 8   Death date        663 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 38.1+ MB

(555338, 9)

Business Partner    0
Customer No.        0
Partner Type        78
Data Origin         136
Title               46307
Marital Status      539301
Occupation          540780
Date of Birth       541894
Death date          554675
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492314 entries, 0 to 492313
Data columns (total 59 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            492314 non-null  int64
 1   Amt Rcvd From Custom  295028 non-null  float64
 2   Amt Rcvd From Ins Co  295028 non-null  float64
 3   Area / Locality       468424 non-null  object
 4   CGST(14%)             295028 non-null  float64
 5   CGST(2.5%)            295028 non-null  float64
 6   CGST(6%)              295028 non-null  float64
 7   CGST(9%)              295028 non-null  float64
 8   CITY                  492313 non-null  object
 9   Cash /Cashless Type   27420 non-null   object
 10  Claim No.             4804 non-null    object
 11  Cust Type             492314 non-null  object
 12  Customer No.          492314 non-null  object
 13  District              492314 non-null  object
 14  Expiry Date           22231 non-null   object
 15  Gate Pass Date        40915 non-null   object
 16  Gate Pass Time        492314 non-null  object
 17  IGST(12%)             295028 non-null  float64
 18  IGST(18%)             295028 non-null  float64
 19  IGST(28%)             295028 non-null  float64
 20  IGST(5%)              295028 non-null  float64
 21  Insurance Company     23591 non-null   object
 22  Invoice Date          492314 non-null  object
 23  Invoice No            492314 non-null  int64
 24  Invoice Time          492314 non-null  object
 25  Job Card No           492314 non-null  int64
 26  JobCard Date          492314 non-null  object
 27  JobCard Time          492314 non-null  object
 28  KMs Reading           492314 non-null  int64
 29  Labour Total          492314 non-null  float64
 30  Make                  492314 non-null  object
 31  Misc Total            492314 non-null  float64
 32  Model                 490789 non-null  object
 33  ODN No.               295028 non-null  float64
 34  OSL Total             492314 non-null  float64
 35  Order Type            492314 non-null  object
 36  Outstanding Amt       295028 non-null  float64
 37  Parts Total           492314 non-null  float64
 38  Pin code              492314 non-null  int64
 39  Plant                 492314 non-null  object
 40  Plant Name1           492314 non-null  object
 41  Policy no.            16882 non-null   object
 42  Print Status          492314 non-null  object
 43  Recovrbl Exp          492314 non-null  float64
 44  Regn No               492298 non-null  object
 45  SGST/UGST(14%)        295028 non-null  float64
 46  SGST/UGST(2.5%)       295028 non-null  float64
 47  SGST/UGST(6%)         295028 non-null  float64
 48  SGST/UGST(9%)         295028 non-null  float64
 49  Service Advisor Name  0 non-null       float64
 50  TDS amount            295028 non-null  float64
 51  Technician Name       255480 non-null  object
 52  Total Amt Wtd Tax.    492314 non-null  float64
 53  Total CGST            295028 non-null  float64
 54  Total GST             295028 non-null  float64
 55  Total IGST            295028 non-null  float64
 56  Total SGST/UGST       295028 non-null  float64
 57  Total Value           295028 non-null  float64
 58  User ID               492314 non-null  object
dtypes: float64(29), int64(5), object(25)
memory usage: 221.6+ MB

(492314, 59)

Unnamed: 0              0
Amt Rcvd From Custom    197286
Amt Rcvd From Ins Co    197286
Area / Locality         23890
CGST(14%)               197286
CGST(2.5%)              197286
CGST(6%)                197286
CGST(9%)                197286
CITY                    1
Cash /Cashless Type     464894
Claim No.               487510
Cust Type               0
Customer No.            0
District                0
Expiry Date             470083
Gate Pass Date          451399
Gate Pass Time          0
IGST(12%)               197286
IGST(18%)               197286
IGST(28%)               197286
IGST(5%)                197286
Insurance Company       468723
Invoice Date            0
Invoice No              0
Invoice Time            0
Job Card No             0
JobCard Date            0
JobCard Time            0
KMs Reading             0
Labour Total            0
Make                    0
Misc Total              0
Model                   1525
ODN No.                 197286
OSL Total               0
Order Type              0
Outstanding Amt         197286
Parts Total             0
Pin code                0
Plant                   0
Plant Name1             0
Policy no.              475432
Print Status            0
Recovrbl Exp            0
Regn No                 16
SGST/UGST(14%)          197286
SGST/UGST(2.5%)         197286
SGST/UGST(6%)           197286
SGST/UGST(9%)           197286
Service Advisor Name    492314
TDS amount              197286
Technician Name         236834
Total Amt Wtd Tax.      0
Total CGST              197286
Total GST               197286
Total IGST              197286
Total SGST/UGST         197286
Total Value             197286
User ID                 0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5619484 entries, 0 to 5619483
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   Unnamed: 0           int64
 1   DBM Order            int64
 2   Order Item           int64
 3   Material             object
 4   Labor Value Number   object
 5   Description          object
 6   Item Category        object
 7   Order Quantity       float64
 8   Target quantity UoM  object
 9   Net value            float64
dtypes: float64(2), int64(3), object(5)
memory usage: 428.7+ MB

(5619484, 10)

Unnamed: 0             0
DBM Order              0
Order Item             0
Material               51629
Labor Value Number     3774033
Description            51629
Item Category          0
Order Quantity         0
Target quantity UoM    51629
Net value              0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant                    438 non-null    object
 1   Name 1                   438 non-null    object
 2   Valuation Area           438 non-null    object
 3   Customer no. - plant     438 non-null    object
 4   Vendor number plant      2 non-null      object
 5   Factory calendar         438 non-null    object
 6   Name 2                   436 non-null    object
 7   House number and street  436 non-null    object
 8   PO Box                   437 non-null    float64
 9   Postal Code              438 non-null    int64
 10  City                     438 non-null    object
 11  Sales organization       433 non-null    object
 12  State                    438 non-null    object
dtypes: float64(1), int64(1), object(11)
memory usage: 44.6+ KB

(438, 13)

Plant                      0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        436
Factory calendar           0
Name 2                     2
House number and street    2
PO Box                     1
Postal Code                0
City                       0
Sales organization         5
State                      0
dtype: int64

# Data Cleaning

In [8]:
cust_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date
0,31,1,1.0,Z001,NaN,NaN,NaN,NaN,NaT
1,32,2,1.0,Z005,NaN,NaN,NaN,NaN,NaT
2,34,4,1.0,Z005,NaN,2.0,NaN,NaN,NaT
3,35,5,1.0,Z005,NaN,NaN,NaN,NaN,NaT
4,42,7,1.0,Z008,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...
555333,PLX506,PLX506,NaN,NaN,NaN,NaN,NaN,NaN,NaT
555334,PLX507,PLX507,NaN,NaN,NaN,NaN,NaN,NaN,NaT
555335,PLX508,PLX508,NaN,NaN,NaN,NaN,NaN,NaN,NaT
555336,PLX555,PLX555,NaN,NaN,NaN,NaN,NaN,NaN,NaT
555337,RSA100,RSA100,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [9]:
cust_df.isnull().sum()

Business Partner    0
Customer No.        0
Partner Type        78
Data Origin         136
Title               46307
Marital Status      539301
Occupation          540780
Date of Birth       541894
Death date          554675
dtype: int64

In [10]:
cust_df["Data Origin"].fillna(0, inplace=True) 
cust_df["Partner Type"].fillna(0, inplace=True) 
cust_df["Title"].fillna(0, inplace=True) 
cust_df["Occupation"].fillna(0, inplace = True) 
cust_df["Marital Status"].fillna(0, inplace=True) 

cust_df["Date of Birth"].fillna('01-01-1900', inplace=True)
cust_df["Death date"].fillna('31-12-3000', inplace=True)

In [11]:
cust_df.isnull().sum()

Business Partner    0
Customer No.        0
Partner Type        0
Data Origin         0
Title               0
Marital Status      0
Occupation          0
Date of Birth       0
Death date          0
dtype: int64

In [12]:
inv_df

,Unnamed: 0,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,Customer No.,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID
0,0,0.0,0.0,MAJIWADA,0.0,0.0,0.0,0.0,Thane,NaN,NaN,Retail,67849,Maharashtra,NaN,NaN,00:00:00,0.0,0.0,0.0,0.0,NaN,2015-01-02,7005200002,11:30:36,168303,2014-12-13,14:29:43,49317,1203.14,GENERAL MOTORS,0.00,SPARK,7.005200e+09,500.06,Paid Service,0.0,2348.75,400601,BC01,THANE,NaN,NO,0.0,KA19MA1291,0.0,0.0,0.0,0.0,NaN,0.0,RUPESH,4051.95,0.0,0.0,0.0,0.0,4051.95,BC01FS1
1,1,0.0,0.0,THNAE,0.0,0.0,0.0,0.0,THNAE,NaN,NaN,Retail,84419,Maharashtra,NaN,NaN,00:00:00,0.0,0.0,0.0,0.0,NaN,2015-01-03,7005200003,10:07:32,173997,2015-01-02,14:12:18,78584,804.26,TATA MOTORS,197.03,INDICA,7.005200e+09,0.00,SMC Value Package,0.0,0.00,400603,BC01,THANE,NaN,NO,0.0,MH43R3046,0.0,0.0,0.0,0.0,NaN,0.0,PRASHANT,1001.29,0.0,0.0,0.0,0.0,1001.29,BC01SA2
2,2,0.0,0.0,THANE,0.0,0.0,0.0,0.0,THANE[W],NaN,NaN,Retail,81055,Maharashtra,NaN,NaN,00:00:00,0.0,0.0,0.0,0.0,NaN,2015-01-03,7005200004,11:12:57,173889,2015-01-02,11:40:44,33985,180.19,MARUTI SUZUKI,0.00,ZEN,7.005200e+09,0.00,Running Repairs,0.0,52.95,400607,BC01,THANE,NaN,NO,0.0,AP09AX0582,0.0,0.0,0.0,0.0,NaN,0.0,IMRAN,233.14,0.0,0.0,0.0,0.0,233.14,BC01SA2
3,3,0.0,0.0,THNAE,0.0,0.0,0.0,0.0,THNAE,NaN,NaN,Retail,84419,Maharashtra,NaN,NaN,00:00:00,0.0,0.0,0.0,0.0,NaN,2015-01-03,7005200005,11:40:44,174158,2015-01-03,10:12:32,78584,0.00,TATA MOTORS,0.00,INDICA,7.005200e+09,0.00,SMC Redemption,0.0,0.00,400603,BC01,THANE,NaN,NO,0.0,MH43R3046,0.0,0.0,0.0,0.0,NaN,0.0,PRASHANT,0.00,0.0,0.0,0.0,0.0,0.00,BC01SA2
4,4,0.0,0.0,THANE,0.0,0.0,0.0,0.0,THANE,NaN,NaN,Retail,18980,Maharashtra,NaN,NaN,00:00:00,0.0,0.0,0.0,0.0,NaN,2015-01-03,7005200006,12:07:17,173860,2015-01-02,10:45:42,50057,1202.97,HYUNDAI,100.00,SANTRO XING,7.005200e+09,499.99,Paid Service,0.0,944.16,400603,BC01,THANE,NaN,NO,0.0,MH04CD9768,0.0,0.0,0.0,0.0,NaN,0.0,DAYANAND,2747.12,0.0,0.0,0.0,0.0,2747.12,BC01SA2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492309,984736,NaN,NaN,.,NaN,NaN,NaN,NaN,Chennai,NaN,NaN,Retail,203820,Tamil Nadu,NaN,NaN,00:00:00,NaN,NaN,NaN,NaN,NaN,2016-06-30,7231000017,14:56:58,400100,2016-06-30,09:15:12,72546,2495.90,MARUTI SUZUKI,374.97,ALTO,NaN,0.00,Paid Service,NaN,1587.28,600058,X405,X405 - NANGAN MOTORS PVT. LTD.,NaN,NO,0.0,TN38Y9343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4458.15,NaN,NaN,NaN,NaN,NaN,X405SA1
492310,984737,NaN,NaN,.,NaN,NaN,NaN,NaN,ADAMBAKKAM,NaN,NaN,Retail,170411,Tamil Nadu,NaN,NaN,00:00:00,NaN,NaN,NaN,NaN,NaN,2016-06-30,7231000018,15:06:52,400092,2016-06-30,08:42:15,18968,2443.47,NISSAN,0.00,MICRA,NaN,0.00,Paid Service,NaN,4388.61,600088,X405,X405 - NANGAN MOTORS PVT. LTD.,NaN,NO,0.0,TN22CK0396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6832.08,NaN,NaN,NaN,NaN,NaN,X405SA1
492311,984738,NaN,NaN,CHENNAI,NaN,NaN,NaN,NaN,CHENNAI,NaN,NaN,Retail,48811,Tamil Nadu,NaN,NaN,00:00:00,NaN,NaN,NaN,NaN,NaN,2016-06-30,7231000019,15:43:56,400082,2016-06-30,08:27:51,177433,2598.92,MAHINDRA & MAHINDRA,0.00,SCORPIO CRDE,NaN,0.00,Paid Service,NaN,6588.79,600044,X405,X405 - NANGAN MOTORS PVT. LTD.,NaN,NO,0.0,TN07BA0211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9187.71,NaN,NaN,NaN,NaN,NaN,X405SA1
492312,984739,NaN,NaN,"DK NAGAR EXTN,",NaN,NaN,NaN,NaN,"Vijaya Nagar, 1 main road,Velacherr",NaN,NaN,Retail,204067,Tamil Nadu,NaN,NaN,00:00:00,NaN,NaN,NaN,NaN,NaN,2016-06-30,7231000020,15:58:59,400545,2016-06-30,12:53:48,22932,11000.00,HONDA,100.00,AMAZE,NaN,0.00,Accidental,NaN,0.00,600042,X405,X405 - NANGAN MOTORS PVT. LTD.,NaN,NO,0.0,TN07BV9290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11100.00,NaN,NaN,NaN,NaN,NaN,X405SA1
492313,984740,NaN,NaN,2ND FLOOR,NaN,NaN,NaN,NaN,saidapet,NaN,NaN,Retail,204288,Tamil Nadu,NaN,NaN,00:00:00,NaN,NaN,NaN,NaN,NaN,2016-06-30,7231000021,17:09:19,400891,2016-06-30,16:54:06,149197,747.78,MARUTI SUZUKI,0.00,WAGONR,NaN,0.00,Running Repairs,NaN,0.00,600016,X405,X405 - NANGAN MOTORS PVT. LTD.,NaN,NO,0.0,TN10T3317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,747.78,NaN,NaN,NaN,NaN,NaN,X405WM1

In [13]:
inv_df.isnull().sum()

Unnamed: 0              0
Amt Rcvd From Custom    197286
Amt Rcvd From Ins Co    197286
Area / Locality         23890
CGST(14%)               197286
CGST(2.5%)              197286
CGST(6%)                197286
CGST(9%)                197286
CITY                    1
Cash /Cashless Type     464894
Claim No.               487510
Cust Type               0
Customer No.            0
District                0
Expiry Date             470083
Gate Pass Date          451399
Gate Pass Time          0
IGST(12%)               197286
IGST(18%)               197286
IGST(28%)               197286
IGST(5%)                197286
Insurance Company       468723
Invoice Date            0
Invoice No              0
Invoice Time            0
Job Card No             0
JobCard Date            0
JobCard Time            0
KMs Reading             0
Labour Total            0
Make                    0
Misc Total              0
Model                   1525
ODN No.                 197286
OSL Total               0
Order Type              0
Outstanding Amt         197286
Parts Total             0
Pin code                0
Plant                   0
Plant Name1             0
Policy no.              475432
Print Status            0
Recovrbl Exp            0
Regn No                 16
SGST/UGST(14%)          197286
SGST/UGST(2.5%)         197286
SGST/UGST(6%)           197286
SGST/UGST(9%)           197286
Service Advisor Name    492314
TDS amount              197286
Technician Name         236834
Total Amt Wtd Tax.      0
Total CGST              197286
Total GST               197286
Total IGST              197286
Total SGST/UGST         197286
Total Value             197286
User ID                 0
dtype: int64

In [77]:
inv_df["Amt Rcvd From Custom"].fillna(0, inplace=True)
inv_df["Amt Rcvd From Ins Co"].fillna(0, inplace=True)
inv_df["CGST(14%)"].fillna(0, inplace=True)
inv_df["CGST(2.5%)"].fillna(0, inplace=True)
inv_df["CGST(6%)"].fillna(0, inplace=True)
inv_df["CGST(9%)"].fillna(0, inplace=True)
inv_df["IGST(12%)"].fillna(0, inplace=True)
inv_df["IGST(18%)"].fillna(0, inplace=True)
inv_df["IGST(28%)"].fillna(0, inplace=True)
inv_df["IGST(5%)"].fillna(0, inplace=True)
inv_df["SGST/UGST(14%)"].fillna(0, inplace=True)
inv_df["SGST/UGST(2.5%)"].fillna(0, inplace=True)
inv_df["SGST/UGST(6%)"].fillna(0, inplace=True)
inv_df["SGST/UGST(9%)"].fillna(0, inplace=True)
inv_df["Total CGST"].fillna(0, inplace=True)
inv_df["Total GST"].fillna(0, inplace=True)
inv_df["Total IGST"].fillna(0, inplace=True)
inv_df["Total SGST/UGST"].fillna(0, inplace=True)
inv_df["Total Value"].fillna(0, inplace=True)
inv_df["Total Amt Wtd Tax."].fillna(0, inplace=True)
inv_df["TDS amount"].fillna(0, inplace=True)
inv_df["Recovrbl Exp"].fillna(0, inplace=True)
inv_df["Outstanding Amt"].fillna(0, inplace=True)
inv_df["Misc Total"].fillna(0, inplace=True)
inv_df["Labour Total"].fillna(0, inplace=True)
inv_df["KMs Reading"].fillna(0, inplace=True)
inv_df["ODN No."].fillna(0, inplace=True)

inv_df["Technician Name"].fillna('NotAvailable', inplace=True)
inv_df["Service Advisor Name"].fillna('NotAvailable', inplace=True)
inv_df["Policy no."].fillna('NotAvailable', inplace=True)
inv_df["Model"].fillna('NotAvailable', inplace=True)
inv_df["Insurance Company"].fillna('NotAvailable', inplace=True)
inv_df["Area / Locality"].fillna('NotAvailable', inplace=True)
inv_df["CITY"].fillna('NotAvailable', inplace=True)
inv_df["Regn No"].fillna('NotAvailable', inplace=True)
inv_df["Cash /Cashless Type"].fillna('NotAvailable', inplace=True)
inv_df["Claim No."].fillna('NotAvailable', inplace=True)

inv_df["Expiry Date"].fillna('31-12-3000', inplace=True)
inv_df["Gate Pass Date"].fillna('31-12-3000', inplace=True)

In [15]:
inv_df.isnull().sum()

Unnamed: 0              0
Amt Rcvd From Custom    0
Amt Rcvd From Ins Co    0
Area / Locality         0
CGST(14%)               0
CGST(2.5%)              0
CGST(6%)                0
CGST(9%)                0
CITY                    0
Cash /Cashless Type     0
Claim No.               0
Cust Type               0
Customer No.            0
District                0
Expiry Date             0
Gate Pass Date          0
Gate Pass Time          0
IGST(12%)               0
IGST(18%)               0
IGST(28%)               0
IGST(5%)                0
Insurance Company       0
Invoice Date            0
Invoice No              0
Invoice Time            0
Job Card No             0
JobCard Date            0
JobCard Time            0
KMs Reading             0
Labour Total            0
Make                    0
Misc Total              0
Model                   0
ODN No.                 0
OSL Total               0
Order Type              0
Outstanding Amt         0
Parts Total             0
Pin code                0
Plant                   0
Plant Name1             0
Policy no.              0
Print Status            0
Recovrbl Exp            0
Regn No                 0
SGST/UGST(14%)          0
SGST/UGST(2.5%)         0
SGST/UGST(6%)           0
SGST/UGST(9%)           0
Service Advisor Name    0
TDS amount              0
Technician Name         0
Total Amt Wtd Tax.      0
Total CGST              0
Total GST               0
Total IGST              0
Total SGST/UGST         0
Total Value             0
User ID                 0
dtype: int64

In [16]:
jtd_df

,Unnamed: 0,DBM Order,Order Item,Material,Labor Value Number,Description,Item Category,Order Quantity,Target quantity UoM,Net value
0,0,22385,180,OSLCC_SRV31,NaN,MACHINING RR.SUSPENSION CHARGE (MAJOR),P010,1.2,MIN,1869.87
1,1,23910,10,1DM279018170117,NaN,ASSY.OIL COOLER (6-PLATE) (VOR,P002,1.0,EA,2151.13
2,2,23910,40,1IS150203BE01,NaN,FRONT WHEEL BEARING/ LUBRICATE,P002,1.0,EA,2552.92
3,3,23910,60,1DM279001990173,NaN,ASSY.CYL.HEAD W /O INJ.(NA W /O,P002,1.0,EA,20360.14
4,4,23910,70,1DM88552790S001SA,NaN,Engine Overhaul Kit -Indica Di,P002,1.0,EA,10691.63
...,...,...,...,...,...,...,...,...,...,...
5619479,5619479,962813,50,ACCT_SRV,ACCDBP0121,DENTING RADIATOR MOUNTING PANEL LOWER,P001,850.0,MIN,1050.00
5619480,5619480,962813,60,ACCT_SRV,ACCDBP0110,DENTING QUARTER PANEL RHS,P001,750.0,MIN,1250.00
5619481,5619481,962813,70,TOYOTA_SRV,TOINEL0029,CHARGING BATTERY & TESTING LOAD,P001,42.0,MIN,223.00
5619482,5619482,962813,80,ACCT_SRV,ACCDEL0093,REPAIR LHS / RHS TAIL LIGHT BOX,P001,450.0,MIN,450.00
5619483,5619483,962813,90,ACCT_SRV,ACCDBP0037,DENTING FRONT BUMPER,P001,1200.0,MIN,2149.99

In [17]:
jtd_df.isnull().sum()

Unnamed: 0             0
DBM Order              0
Order Item             0
Material               51629
Labor Value Number     3774033
Description            51629
Item Category          0
Order Quantity         0
Target quantity UoM    51629
Net value              0
dtype: int64

In [19]:
jtd_df["Material"].fillna('NotAvailable', inplace=True)
jtd_df["Description"].fillna('NotAvailable', inplace=True)
jtd_df["Target quantity UoM"].fillna('NotAvailable', inplace=True)
jtd_df["Labor Value Number"].fillna('NotAvailable', inplace=True)

In [20]:
jtd_df.isnull().sum()

Unnamed: 0             0
DBM Order              0
Order Item             0
Material               0
Labor Value Number     0
Description            0
Item Category          0
Order Quantity         0
Target quantity UoM    0
Net value              0
dtype: int64

In [18]:
plant_df

,Plant,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State
0,BC07,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,NaN,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu
1,BC30,SAS NAGAR - MOHALI,BC30,PLBC30,PLBC30,IN,NaN,"C-118, Phase 07,",160055.0,160055,Mohali,MFCS,Punjab
2,X001,X001 - AUTO PLANET WHEELS,X001,PLX001,NaN,IN,Thane,"Unit No.3, Kothari Compound,",400610.0,400610,Thane,MFCA,Maharashtra
3,X002,X002 - BHANDARI INDUSTRIES PVT,X002,PLX002,NaN,IN,Ghaziabad,"18/1, C Site 4, Sahibabad",201010.0,201010,Ghaziabad,MFCA,Uttar Pradesh
4,X003,X003 - Om Sri Satya Sai Automo,X003,PLX003,NaN,IN,Bengaluru,"#75, Sy.No. 83/2, Panathur Mai",560087.0,560087,Bengaluru,MFCB,Karnataka
5,X005,X005 - KLN MOTORS,X005,PLX005,NaN,IN,Chennai,"No.8 (NP) Developed Plot,",600032.0,600032,Chennai,MFCB,Tamil Nadu
6,X006,X006 - A.M.MOTORS,X006,PLX006,NaN,IN,Mumbai,"8, Mira, Behind Ajit Palace Ho",401104.0,401104,Thane,MFCB,Maharashtra
7,X007,X007 - OM SRI SATYA SAI AUTOMO,X007,PLX007,NaN,IN,Bengaluru,"Seegehalli main road,",560037.0,560037,Bengaluru,MFCB,Karnataka
8,X008,X008- AAKASH AUTO (Puducherry),X008,PLX008,NaN,IN,Puducherry,"145/2, Villiyanur main road,",605110.0,605110,Puducherry,MFCC,Puducherry
9,X010,X010 - LVM MOTORS,X010,PLX010,NaN,IN,Chennai,"B- 49 Emerald Nagar, SIPCOT,",632406.0,632406,Ranipet,MFCD,Tamil Nadu
10,X011,X011- AAKASH AUTO (Villupuram),X011,PLX011,NaN,IN,Chennai,"No 7, Trichy Trunk Road,",605401.0,605401,Villupuram,MFCD,Tamil Nadu
11,X012,X012 - SR CAR CARE,X012,PLX012,NaN,IN,Tamil Nadu,"No 5, Bye Pass Road,",608001.0,608001,Chidambaram,MFCD,Tamil Nadu
12,X013,X013 - SAI AUTO WORKS,X013,PLX013,NaN,IN,Tamil Nadu,"NH 45 C, Rainbow Nagar Near Mo",607308.0,607308,Neyveli,MFCD,Tamil Nadu
13,X014,X014 - NANGAN MOTORS PVT LTD.,X014,PLX014,NaN,IN,Ambur,"0/1, M.C.Road,",635802.0,635802,Ambur,MFCD,Tamil Nadu
14,X016,X016 - KHUTWAD MOTORS,X016,PLX016,NaN,IN,Boripardhi,"Khutwad Complex,",412203.0,412203,Boripardhi,MFCD,Maharashtra
15,X017,X017 - HEM KIRAN DIESELS,X017,PLX017,NaN,IN,Kolhapur,"1227-E Rajaram Road,",416008.0,416008,Kolhapur,MFCD,Maharashtra
16,X018,X018 - EXPRESS WHEELS AUTO SER,X018,PLX018,NaN,IN,Shirur,"Gut No. 1340,",412210.0,412210,Shirur,MFCD,Maharashtra
17,X020,X020 - SURYABALA SERVICE,X020,PLX020,NaN,IN,Coimbatore,"Subbiah Naidu Thottam,",641039.0,641039,Coimbatore,MFCC,Tamil Nadu
18,X021,X021 - THE TRUE SAI MOTORSS,X021,PLX021,NaN,IN,Salem,"1/9, Court Road,",636007.0,636007,Salem,MFCC,Tamil Nadu
19,X022,X022 - ARASU CAR ACCESSORIES,X022,PLX022,NaN,IN,Thanjavur,"# 20, Sanjeeve Nagar,",613005.0,613005,Thanjavur,MFCD,Tamil Nadu
20,X023,X023 - ROYAL KRR AUTOS,X023,PLX023,NaN,IN,Tirupur,"8(1A), KRR Layout, Karuvampala",641604.0,641604,Tirupur,MFCC,Tamil Nadu
21,X024,X024 - ARASU CAR ACC (TRICHY),X024,PLX024,NaN,IN,Trichy,"1, JP Nagar,",620009.0,620009,Tiruchirappalli,MFCC,Tamil Nadu
22,X025,X025 - SHIVALIK AUTOMOBILES,X025,PLX025,NaN,IN,Punjab,"NH-95,",142001.0,142001,Moga,MFCD,Punjab
23,X026,X026 - MAHADEVI SERVICE CENTER,X026,PLX026,NaN,IN,PUNE,"151/1, Mahalunge,",410501.0,410501,Pune,MFCD,Maharashtra
24,X027,X027 - RAHUL AUTO SERV. PVT.,X027,PLX027,NaN,IN,Pune,"Survey No. 167, adjacent to Pa",410506.0,410506,Pune,MFCD,Maharashtra
25,X028,X028 - SAIDEEP CAR CARE,X028,PLX028,NaN,IN,Ahmednagar,"Survey No. 55/1/2B/1, B/H New",414001.0,414001,Ahmednagar,MFCD,Maharashtra
26,X029,X029 - SWAMI AUTO CARE PVT LTD,X029,PLX029,NaN,IN,Zirakpur,"Singhpura,",140603.0,140603,Zirakpur,MFCD,Punjab
27,X031,X031 - ANUSHRI MOTORS,X031,PLX031,NaN,IN,Pollachi,"279,",642003.0,642003,Pollachi,MFCD,Tamil Nadu
28,X032,X032 - SBBS MOTORS,X032,PLX032,NaN,IN,Dharmapuri,"5/309A, Sagadevan Street,",636705.0,636705,Dharmapuri,MFCD,Tamil Nadu
29,X033,X033 - TRISTAR INDIA TRADING,X033,PLX033,NaN,IN,Shimoga,"Plot No. 9/3 # 897/3,",577202.0,577202,Shimoga,MFCD,Karnataka
30,X034,X034 - SOHAMM MOTORS,X034,PLX034,NaN,IN,Aurangabad,"Plot No. C-27,",431006.0,431006,Aurangabad,MFCD,Maharashtra
31,X035,X035 - DOCTOR CARS,X035,PLX035,NaN,IN,Pune,"390/2B, Opposite Sandvik Asia",411012.0,411012,Pune,MFCC,Maharashtra
32,X036,X036 - X-PRESS MOTORS,X036,PLX036,NaN,IN,Madurai,"D-25, SIDCO Industrial Estate,",625008.0,625008,Madurai,MFCC,Tamil Nadu
33,X037,X037 - DHEERAJ MOTORS,X037,PLX037,NaN,IN,Kurnool,"D. No. 45-142-70-5-B, NH-7 Roa",518003.0,518003,Kurnool,MFCD,Andhra Pradesh
34,X039,X039 - SAI AUTOMOBILES,X039,PLX039,NaN,IN,Chennai,"No: 4/905, GNT Road,",600052.0,600052,Chennai,MFCD,Tamil Nadu
35,X041,X041 - VARDAJYOTI AUTOMOBILES,X041,PLX041,NaN,IN,Meerut,"Madhuban,",250002.0,250002,Meerut,MFCD,Uttar Pradesh
36,X042,X042 - CAR PLANET ENTERPRISES,X042,PLX042,NaN,IN,Raipur,"Opp. Deendayal Upadhyay Nagar,",492001.0,492001,Raipur,MFCC,Chhattisgarh
37,X044,X044 - KANMANI CAR CARE,X044,PLX044,NaN,IN,Dindigul,No. 250 Trichy By Pass Road,624005.0,624005,Dindigul,MFCD,Tamil Nadu
38,X045,X045 - BA MOTORS,X045,PLX045,NaN,IN,Rohtak,"Near BA NISSAN PVT. LTD,",124001.0,124001,Rohtak,MFCD,Haryana
39,X046,X046 - SVERA AUTOMOBILES,X046,PLX046,NaN,IN,Jhajjar,"Plot No - 1309,",124103.0,124103,Jhajjar,MFCD,Haryana
40,X047,X047 - X-PRESS MOTORS,X047,PLX047,NaN,IN,Tirunelveli,Plotno:142 Trivandrum Bye Pass,627002.0,627002,Tirunelveli,MFCC,Tamil Nadu
41,X048,X048 - HARI KRISHNA AUTOMOBILE,X048,PLX048,NaN,IN,Nagercoil,"NMC-1/344A , Jayajothi Buildin",629001.0,629001,Nagercoil,MFCD,Tamil Nadu
42,X049,X049 - SHENBAGAM MOTORS,X049,PLX049,NaN,IN,Tuticorin,"1D/219, Meelavittan Main Road,",628002.0,628002,Tuticorin,MFCD,Tamil Nadu
43,X050,X050 - VISHWATMAK AUTOMOBILES,X050,PLX050,NaN,IN,Vadali Bhoi,"Gutt No.514,Mumbai Agra Highwa",423117.0,423117,Vadali Bhoi,MFCD,Maharashtra
44,X051,X051 - RAJATHI AUTO CARE PRIVA,X051,PLX051,NaN,IN,Coimbatore,"No.5, Thottipalayam Privu, Raj",641014.0,641014,Coimbatore,MFCC,Tamil Nadu
45,X052,X052 - XPRESS MOTORS,X052,PLX052,NaN,IN,Madurai,"Shed No.I-4, Industrial Estat",625102.0,625102,Madurai,MFCC,Tamil Nadu
46,X053,X053 - PREM AUTOMOBILES,X053,PLX053,NaN,IN,Bhagpat,"Plot No. 525,",250609.0,250609,Bhagpat,MFCD,Uttar Pradesh
47,X054,X054 - HOREB AUTOMOBILES,X054,PLX054,NaN,IN,Ongole,"7-38, NH-5, Opp. Auto Nagar,",532001.0,532001,Ongole,MFCD,Andhra Pradesh
48,X055,X055 - S K AUTOMOBILES,X055,PLX055,NaN,IN,Rajahmundry,"84-1-2, Beside ONGC Base Compl",533106.0,533106,Rajahmundry,MFCD,Andhra Pradesh
49,X056,X056 - SRI RAJABABU AUTOMOTIVE,X056,PLX056,NaN,IN,Vijayawada,"RS No:- 324/3A,",520008.0,520008,Vijayawada,MFCC,Andhra Pradesh
50,X057,X057 - RANGANATHA SWAMY MOTORS,X057,PLX057,NaN,IN,Hassan,"Survey No-188/1, NH-48,",573201.0,573201,Hassan,MFCD,Karnataka
51,X058,X058 - ASR AUTOMOBILES,X058,PLX058,NaN,IN,Sonepat,"Opposite Suraj Petrol Pump ,",131001.0,131001,Sonepat,MFCD,Haryana
52,X060,X060 - SHIVANSH AUTOMOTIVE,X060,PLX060,NaN,IN,Chhindwara,"Village - Sarra,",480001.0,480001,Chhindwara,MFCD,Madhya Pradesh
53,X061,X061 - APS MOTORCARE PVT LTD,X061,PLX061,NaN,IN,Rishikesh,"581, Laxman Jhoola Road,",249201.0,249201,Rishikesh,MFCD,Uttarakhand
54,X062,X062 - S N S MOTORS MYSORE,X062,PLX062,NaN,IN,Mysore,"No. 2421, Opp Yashaswini Kalya",570017.0,570017,Mysore,MFCC,Karnataka
55,X063,X063 - CHAKARAVARTHY AUTOMOTIV,X063,PLX063,NaN,IN,Hyderabad,"Survey No 146/3, N.H Road,",515004.0,515004,Anantapur,MFCD,Andhra Pradesh
56,X064,X064 - SHIVAM ENTERPRISES,X064,PLX064,NaN,IN,Hisar,"Old Industrial Area,",125005.0,125005,Hisar,MFCD,Haryana
57,X065,X065 - PIONEER AUTOWORLD,X065,PLX065,NaN,IN,Greater Noida,A Unit Of Pioneer Automotive E,201306.0,201306,Greater Noida,MFCB,Uttar Pradesh
58,X066,X066 - REVATHI SERVICE CENTRE,X066,PLX066,NaN,IN,Palani,"189/7, Opp New RTO Office,",624601.0,624601,Palani,MFCD,Tamil Nadu
59,X068,X068 - VAKA CARS,X068,PLX068,NaN,IN,Thirupathi,"#297, Sanjay Gandhi Colony,",517501.0,517501,Thirupathi,MFCD,Andhra Pradesh
60,X072,X072 - PRABHAV PREMIUM AUTOMOB,X072,PLX072,NaN,IN,Abohar,"Plot No 382,",152116.0,152116,Abohar,MFCD,Punjab
61,X073,X073- KRITI AUTOMOBILE REPAIR,X073,PLX073,NaN,IN,Nashik,"Plot A-6, MIDC,",422007.0,422007,Nashik,MFCD,Maharashtra
62,X074,X074 - VISHWA MOTORS,X074,PLX074,NaN,IN,Shrigonda,"Nr. Hotel R. K. Garden,",413701.0,413701,Shrigonda,MFCD,Maharashtra
63,X075,X075 - FUTUREVISION INNOVATION,X075,PLX075,NaN,IN,Agra,"14 Km Milestone,",282007.0,282007,Agra,MFCD,Uttar Pradesh
64,X076,X076 - CAR X CARE,X076,PLX076,NaN,IN,Firozabad,"Chameli Bagh, Near Raja Ka Taa",283203.0,283203,Firozabad,MFCD,Uttar Pradesh
65,X079,X079 - SHREE R V CAR CARE,X079,PLX079,NaN,IN,Kolar,"No 1064/ 442, Next to R V Inte",563101.0,563101,Kolar,MFCD,Karnataka
66,X080,X080 - KHAMLA MOTORS,X080,PLX080,NaN,IN,Nagpur,"E-4/2, MIDC, Industrial Area,",440028.0,440028,Nagpur,MFCB,Maharashtra
67,X081,X081 - GEO MOTORS,X081,PLX081,NaN,IN,Kottayam,"NP/XI/216 E,",686013.0,686013,Kottayam,MFCD,Kerala
68,X082,X082 - A&P MOTORS,X082,PLX082,NaN,IN,Khammam,"Plot No 200,201 Pragathi Co-Op",507003.0,507003,Khammam,MFCD,Telangana
69,X083,X083 - EXCELLENT SERVICE,X083,PLX083,NaN,IN,Suryapet,"Survey No. 726, A/4,",508213.0,508213,Suryapet,MFCD,Telangana
70,X084,X084 - RM AUTOMOTIVE SERVICES,X084,PLX084,NaN,IN,Vijayapura,"Sy No. 449/4, Mantri Colony,",586102.0,586102,Vijayapura,MFCD,Karnataka
71,X085,X085 - SRI MOTORS,X085,PLX085,NaN,IN,Chennai,"No 156, Pazhaveli Bye Pass,",603111.0,603111,Chengalpattu,MFCD,Tamil Nadu
72,X086,X086 - STRIKER AUTOMOBLIES,X086,PLX086,NaN,IN,Bilaspur,"Plot No. 4-5,",174001.0,174001,Bilaspur,MFCD,Himachal Pradesh
73,X089,X089 - AKOLA NATIONAL GARAGE,X089,PLX089,NaN,IN,Akola,"Beside Anapurna Mata Mandir,",444005.0,444005,Akola,MFCD,Maharashtra
74,X091,X091 - HARIKRIPA ENTERPRISES,X091,PLX091,NaN,IN,INDORE,"54, Udyog Nagar,",452001.0,452001,Indore,MFCC,Madhya Pradesh
75,X092,X092 - EXCEL AUTO CORP. PVT. L,X092,PLX092,NaN,IN,Indore,"20/4/11, Lasudia Mori,",452010.0,452010,Indore,MFCC,Madhya Pradesh
76,X095,X095 - NATIONAL AUTOMOBILE,X095,PLX095,NaN,IN,Sikar,"NH-11, Gokulpura Bypass,",332001.0,332001,Sikar,MFCD,Rajasthan
77,X097,X097 - KAINIKKARA MOTORS,X097,PLX097,NaN,IN,Pathanamitta,"P-277/13-3 P-277/12-2, K-277/1",689653.0,689653,Pathanamitta,MFCD,Kerala
78,X098,X098 - KAPOOR MOTORS,X098,PLX098,NaN,IN,Una,"Opp R.T.O Barrier,",174315.0,174315,Una,MFCD,Himachal Pradesh
79,X099,X099 - AUTO WORLD CAR CARE,X099,PLX099,NaN,IN,Nashik,"Plot # 9, Pethe Nagar Road,",422009.0,422009,Nashik,MFCD,Maharashtra
80,X101,X101 - ARIHANT AUTO,X101,PLX101,NaN,IN,Indapur,"236/2/E Pune-Solapur Road,",413106.0,413106,Indapur,MFCD,Maharashtra
81,X102,X102 - WEST COAST AUTOMOTIVE,X102,PLX102,NaN,IN,Mangalore,"No.27-16 (27-16CP6),",575007.0,575007,Mangalore,MFCB,Karnataka
82,X103,X103 - DAYAL MOTORS,X103,PLX103,NaN,IN,Chomu,"Near, Bhanwaria Hospital,",303702.0,303702,Chomu,MFCD,Rajasthan
83,X105,X105 - MSK CARS,X105,PLX105,NaN,IN,Erode,"100/17, 100/18, Urc Nagar Piri",638009.0,638009,Erode,MFCD,Tamil Nadu
84,X106,X106 - TRS MOTORS,X106,PLX106,NaN,IN,Dewas,"In front of Bhakti Avenue,",455001.0,455001,Dewas,MFCD,Madhya Pradesh
85,X107,X107 - DIXIT MOTORS,X107,PLX107,NaN,IN,Wardha,NaN,442001.0,442001,Wardha,MFCD,Maharashtra
86,X108,X108 - PADMA SHREE MOTORS,X108,PLX108,NaN,IN,Nagda,"Survey No. 66/9, Betma Road Ka",454774.0,454774,Nagda,MFCD,Madhya Pradesh
87,X109,X109 - NANGAN MOTORS PVT. LTD,X109,PLX109,NaN,IN,Chennai,"Plot No. 86C and 86D, 2nd Main",600058.0,600058,Chennai,MFCB,Tamil Nadu
88,X110,X110 - KALYAN SERVICES,X110,PLX110,NaN,IN,Coimbatore,"4/5 C, Union Road,",641030.0,641030,Coimbatore,MFCC,Tamil Nadu
89,X111,X111 - RUDRA MOTORS,X111,PLX111,NaN,IN,Amritsar,"Opposite, Ryan international S",143001.0,143001,Amritsar,NaN,Punjab
90,X112,X112 - PATNA WHEELS POINT,X112,PLX112,NaN,IN,Patna,"Ashiyana Digha Road,",800025.0,800025,Patna,MFCC,Bihar
91,X113,X113 - S G AUTOMOTIVES,X113,PLX113,NaN,IN,Mangalore,"Site No - 9/10,",575019.0,575019,Mangalore,MFCC,Karnataka
92,X114,X114 - A J MOTORWORKS,X114,PLX114,NaN,IN,Bhopal,"4/1 Chuna Bhatti, Kolar Road",462016.0,462016,Bhopal,MFCD,Madhya Pradesh
93,X115,X115 - LOHIA CAR CARE,X115,PLX115,NaN,IN,Ujjain,"Adjoining Shree Vardhan Hotel,",456006.0,456006,Ujjain,MFCD,Madhya Pradesh
94,X118,X118 - SURBHI GLOBAL PVT. LTD,X118,PLX118,NaN,IN,Gwalior,"Portion of Survey no 860,",474002.0,474002,Gwalior,MFCD,Madhya Pradesh
95,X119,X119 - VIVEK SERVICES,X119,PLX119,NaN,IN,Buxar,"Jaso Road,",802101.0,802101,Buxar,MFCD,Bihar
96,X121,X121 - MANICK ENTERPRISES,X121,PLX121,NaN,IN,Belgaum,"N15, Industrial Estate,",590008.0,590008,Belgaum,MFCC,Karnataka
97,X122,X122 - S & B AUTOMOBILE,X122,PLX122,NaN,IN,Barh,"Plot No - 174&159, Khata No- 1",803213.0,803213,Bahr,MFCD,Bihar
98,X123,X123 - WHEELOCITY CAR SERVICES,X123,PLX123,NaN,IN,Bhagalpur,"Khasara no 29, At Post Khiriba",812005.0,812005,Bhagalpur,MFCD,Bihar
99,X124,X124 - ZEF MOTORS,X124,PLX124,NaN,IN,Kochi,"Near Vallathol Junction,",682021.0,682021,Kochi,MFCC,Kerala
100,X125,X125 - SHRI WARDHMAN MOTO CORP,X125,PLX125,NaN,IN,Bhopal,"18/1, Sector G, JK Main Road,",462023.0,462023,Bhopal,MFCD,Madhya Pradesh
101,X126,X126 - M.P AUTO VEHICLES PVT.,X126,PLX126,NaN,IN,Varanasi,"B38/2A 3 & 4, Gopal Vihar Colo",221010.0,221010,Varanasi,MFCD,Uttar Pradesh
102,X127,X127 - MY SUPREME,X127,PLX127,NaN,IN,Neemuch,"Near Naka No. 7, Mhow Road.",458441.0,458441,Neemuch,MFCD,Madhya Pradesh
103,X128,X128 - SRI LAKSHMI AUTOMOBILES,X128,PLX128,NaN,IN,Thiruvarur,"TS No: 408/13, Nagai Bye Pass",610001.0,610001,Thiruvarur,MFCD,Tamil Nadu
104,X129,X129 - A.V. AUTOMOBILES,X129,PLX129,NaN,IN,Pinjore,"Pinjore Baddi Highway,",134102.0,134102,Pinjore,MFCD,Haryana
105,X131,X131 - LEELA AUTOMOBILE,X131,PLX131,NaN,IN,Bahraich,"Akbarpura Nai Basti ,Kisan P.G",271801.0,271801,Bahraich,MFCD,Uttar Pradesh
106,X132,X132 - KATIYAR MANGALAM AUTOMO,X132,PLX132,NaN,IN,Farrukhbad,"Khasra 523,Gram Satanpur",209625.0,209625,Farrukhbad,MFCD,Uttar Pradesh
107,X133,X133 - SRI BALAJI MOTORS,X133,PLX133,NaN,IN,Avadi,"S No 694, Avadi Poonamallee Hi",600071.0,600071,Avadi,MFCD,Tamil Nadu
108,X135,X135 - S P JIRAPURE MOTORS,X135,PLX135,NaN,IN,Yavatmal,"Plot No. 18-21,25-26, Jam road",445001.0,445001,Yavatmal,MFCD,Maharashtra
109,X136,X136 - SUNRISE AUTO CARE,X136,PLX136,NaN,IN,Jaipur,"A-243, Road No. 6,",302013.0,302013,Jaipur,MFCD,Rajasthan
110,X138,X138 - HIM AUTOS,X138,PLX138,NaN,IN,Kullu,"Village- mahili, District & Te",175129.0,175129,Kullu,MFCD,Himachal Pradesh
111,X139,X139 - INDRADHANUSH AUTOMOBILE,X139,PLX139,NaN,IN,Bikramganj,"SH15, Bikramganj Dehri Road, B",802212.0,802212,Bikramganj,MFCD,Bihar
112,X140,X140 - SRI RAJARAJESHWARI SERV,X140,PLX140,NaN,IN,Hubballi,"Plot No - 157/1a, Opp State Ex",580025.0,580025,Hubballi,MFCC,Karnataka
113,X146,X146 - RUGRUT MOTORS,X146,PLX146,NaN,IN,Pune,"Sr No 34/1A, Pune-Solapur Road",412307.0,412307,Pune,MFCD,Maharashtra
114,X147,X147 - SPECTRUM AUTOMOTIVES,X147,PLX147,NaN,IN,X147 - SPECTRUM AUTOMOTIVES,"#174/1, Sanklapur,",583201.0,583201,Hospet,MFCD,Karnataka
115,X149,X149 - SARVADNYA AUTO CARE LAT,X149,PLX149,NaN,IN,Latur,"No-1 Chawk ,Near Dic Office,",413531.0,413531,Latur,MFCD,Maharashtra
116,X150,X150 - S K CAR CARE,X150,PLX150,NaN,IN,Karaikal,"685/1, Barathiyar road,",609609.0,609609,Karaikal,MFCD,Puducherry
117,X154,X154 - G.K.CAR ZONE,X154,PLX154,NaN,IN,Thiruvallur,"No 6, C.V Naidu Salai,",602001.0,602001,Thiruvallur,MFCD,Tamil Nadu
118,X155,X155 - AVEER AUTO SPARES AND S,X155,PLX155,NaN,IN,Chhatarpur,"Plot no 261, Behind Jawahar Pe",471001.0,471001,Chhatarpur,MFCD,Madhya Pradesh
119,X156,X156 - MANGLAM AUTOMOBILES,X156,PLX156,NaN,IN,Ratlam,"1098/4- 1098/19,",457001.0,457001,Ratlam,MFCD,Madhya Pradesh
120,X157,X157 - PYDI AUTOMOTIVE LLP,X157,PLX157,NaN,IN,Sirkakulam,"Sy.No. 77-11, NH-16, Kusalapur",532410.0,532410,Sirkakulam,MFCD,Andhra Pradesh
121,X159,X159 - BHANDARI SERVICE CENTRE,X159,PLX159,NaN,IN,Khargone,"Khasra No 10, Halka No 42, Nav",451001.0,451001,Khargone,MFCD,Madhya Pradesh
122,X160,X160 - AMRIT SERVICE STATION,X160,PLX160,NaN,IN,Khandwa,"143/8, Indore Road,",450001.0,450001,Khandwa,MFCD,Madhya Pradesh
123,X161,X161 - ADVANCE AUTO SERVICES,X161,PLX161,NaN,IN,Chandigarh,"Plot Number-81,",160002.0,160002,Chandigarh,MFCC,Chandigarh
124,X164,X164 - EQRA AUTO,X164,PLX164,NaN,IN,Udaipur,"Plot No 10 , Opposite A- one G",313001.0,313001,Udaipur,MFCD,Rajasthan
125,X166,X166 - ANAND AUTOMOTIVE,X166,PLX166,NaN,IN,Gwalior,"Plot no. 16, Industrial Area,",474001.0,474001,Gwalior,MFCD,Madhya Pradesh
126,X167,X167 - MANAK MOTORS P LTD,X167,PLX167,NaN,IN,Jodhpur,"Parshwanath Colony,",342001.0,342001,Jodhpur,NaN,Rajasthan
127,X169,X169 - DREAMWORKS AUTOMOTIVE,X169,PLX169,NaN,IN,Kishangarh,"C\o Rupalo Rawalo, Main Highw",305801.0,305801,Kishangarh,MFCD,Rajasthan
128,X170,X170 - S K AUTOMOBILES,X170,PLX170,NaN,IN,Jhunjhunu,"Plot no - G60B, Riico Industri",333001.0,333001,Jhunjhunu,MFCD,Rajasthan
129,X171,X171 - SRI OM MOTORS,X171,PLX171,NaN,IN,Rajashtan,Near Pugal road railway crossi,334001.0,334001,Bikaner,MFCD,Rajasthan
130,X172,X172 - MARRCO MACHINERIES,X172,PLX172,NaN,IN,Kota,"G-560a, Industrial Area Under",324005.0,324005,Kota,MFCD,Rajasthan
131,X173,X173 - TRIMURTI AUTOMOBILES,X173,PLX173,NaN,IN,Pune,"Gut no 133,",412205.0,412205,Pune,MFCD,Maharashtra
132,X174,X174 - ANKITHA MOTORS,X174,PLX174,NaN,IN,Hyderabad,"1-115/99, Sy No 99,",500049.0,500049,Hyderabad,MFCB,Telangana
133,X175,X175 - SPYNS AUTO,X175,PLX175,NaN,IN,Hyderabad,"Sy No :- 66/4, Opp Big Baazar,",500074.0,500074,Hyderabad,MFCD,Telangana
134,X177,X177 - MAHAMAYA MOTORS,X177,PLX177,NaN,IN,Shahpura,"NH -8, Near Essar Petrol Pump,",311404.0,311404,Shahpura,MFCD,Rajasthan
135,X179,X179 - CHAUDHARY CAR SERVICE C,X179,PLX179,NaN,IN,Khair,"Khet No 11 Gomat Chauraha,",202135.0,202135,Khair,MFCD,Uttar Pradesh
136,X180,X180 - RAMSUN ADVANTAGE,X180,PLX180,NaN,IN,Pudukottai,"6781/1, 6781/2, New Street,",622001.0,622001,Pudukottai,MFCD,Tamil Nadu
137,X183,X183 - MANALI AUTO WORLD,X183,PLX183,NaN,IN,Sangamner,Opp Amrutvaini Engineering Col,422608.0,422608,Sangamner,MFCD,Maharashtra
138,X185,X185 - GUPTA CAR CARE,X185,PLX185,NaN,IN,Rajsamand,"Plot no 1682, Gupta Car Care,",313324.0,313324,Rajsamand,MFCC,Rajasthan
139,X186,X186 - AISHWARYA MOTORS,X186,PLX186,NaN,IN,Kalaburagi,"Survey No. 99,",585102.0,585102,Kalaburagi,MFCD,Karnataka
140,X187,X187 - MOTIWALA SERVICES,X187,PLX187,NaN,IN,Aurangabad,"CTS no 14536/3, Shit no 118,",431001.0,431001,Aurangabad,MFCD,Maharashtra
141,X188,X188 - SONA AUTOMOBILES,X188,PLX188,NaN,IN,Rosera,"Old Bus Stand, Ward No.-09, P.",848210.0,848210,Rosera,MFCD,Bihar
142,X190,X190 - NITHIYA MOTORS,X190,PLX190,NaN,IN,Bengaluru,"Sy No: 39/1b, 39/2,",562107.0,562107,Bengaluru,MFCD,Karnataka
143,X191,X191 - BABA MOTORS,X191,PLX191,NaN,IN,Hingoli,"Gut No - 221/5, Aundha Road,",431513.0,431513,Hingoli,MFCD,Maharashtra
144,X192,X192 - POKATTIL MOTORS,X192,PLX192,NaN,IN,Kottakkal,"1/3B, Athirumada,",676552.0,676552,Kottakkal,MFCD,Kerala
145,X194,X194 - MNC AUTOMOBILES,X194,PLX194,NaN,IN,Rajahmundry,"Survey no 222/2, Near NH-16 -",533105.0,533105,Rajahmundry,MFCD,Andhra Pradesh
146,X196,X196 - BHATTAD AUTO SERVICES,X196,PLX196,NaN,IN,Ojhar,"2436/2/1, Panchwad Nagar, N.H.",422207.0,422206,Nashik,MFCD,Maharashtra
147,X198,X198 - S G AUTOMOTIVE,X198,PLX198,NaN,IN,Udupi,"S.No 97/4AP3, Opposite Bharath",585105.0,585105,Udupi,MFCD,Karnataka
148,X199,X199 - RUDRA AUTOCARE,X199,PLX199,NaN,IN,Ambikapur,"Beside Rawat Residency,",497001.0,497001,Ambikapur,MFCD,Chhattisgarh
149,X201,X201 - ADITYA AUTO WORLD,X201,PLX201,NaN,IN,Shamli,"Khasra No- 612 Me, Kairana Ro",247776.0,247776,Shamli,MFCD,Uttar Pradesh
150,X202,X202 - BHARATH MOTORS,X202,PLX202,NaN,IN,Guntur,"#155A, Opp Rayapati Veeraiah C",522034.0,522034,Guntur,MFCD,Andhra Pradesh
151,X203,X203 - B.M.M AUTOMOBILE SERVIC,X203,PLX203,NaN,IN,Proddatur,S.No 542/1 Industrial Developm,516360.0,516360,Proddatur,MFCD,Andhra Pradesh
152,X204,X204 - SREEDEVI AUTOMOTIVE SER,X204,PLX204,NaN,IN,Kakinada,"2-540, 2-541, Ramanayyapeta,",533001.0,533001,Kakinada,MFCD,Andhra Pradesh

In [21]:
plant_df.isnull().sum()

Plant                      0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        436
Factory calendar           0
Name 2                     2
House number and street    2
PO Box                     1
Postal Code                0
City                       0
Sales organization         5
State                      0
dtype: int64

In [22]:
plant_df["Vendor number plant"].fillna('NotAvailable', inplace = True)
plant_df["House number and street"].fillna('NotAvailable', inplace = True)
plant_df["Sales organization"].fillna('NotAvailable', inplace = True)

plant_df["PO Box"].fillna(plant_df["Postal Code"], inplace = True)
plant_df["Name 2"].fillna(plant_df["City"],inplace = True)

In [23]:
plant_df.isnull().sum()

Plant                      0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        0
Factory calendar           0
Name 2                     0
House number and street    0
PO Box                     0
Postal Code                0
City                       0
Sales organization         0
State                      0
dtype: int64

# Merging DataFrame

In [108]:
inv_df["Plant"]

BC03    28615
BC01    14483
BC05    13323
BC26    13253
BC06    12752
BC07    11815
BC20    10259
BC08    10146
BC13    9990
BC23    9521
BC17    8631
BC15    8343
BC02    8209
BC28    8053
BC34    7483
BC30    7403
BC31    6655
BC12    6577
X006    6505
BC16    5946
BC24    5888
BC19    5812
X025    5497
BC29    5244
BC25    5103
X013    4971
BC22    4911
BC33    4905
BC18    4873
BC04    4681
X020    4432
X012    4427
X036    4286
X022    4079
X102    4026
X005    3993
X007    3742
X014    3639
X062    3610
BC21    3506
X034    3443
BC32    3387
BC27    3347
X017    3328
X029    3284
X003    3267
X033    3264
X021    3107
X024    3022
X109    2949
X023    2857
X103    2831
X047    2756
X238    2670
BC11    2655
X049    2627
X080    2525
X098    2514
X054    2504
X010    2446
X035    2385
X175    2364
X051    2331
X082    2304
X039    2273
X032    2223
X052    2173
X125    2132
X079    2102
X110    2099
X128    2088
X127    2077
X060    2027
X046    2009
X136    1984
X027    1955
X016    1929
X085    1914
X113    1902
X057    1864
X279    1857
X066    1853
X031    1852
X008    1779
X048    1760
X156    1566
X063    1543
X011    1540
X204    1520
X233    1384
X154    1379
X126    1374
X187    1373
X186    1364
X099    1336
X018    1328
X044    1320
X037    1314
X101    1314
X076    1269
X167    1266
X140    1250
X114    1194
X112    1165
X147    1155
X171    1141
X129    1132
X259    1044
X086    1023
X224    1020
X105    1013
X192    991
X209    966
X091    955
X249    926
X327    901
X084    890
X170    886
X001    883
X218    868
X124    865
X056    846
X172    824
X095    810
X068    796
X118    785
X053    784
X245    764
X064    756
X028    746
X106    735
X149    728
X243    721
X328    719
X386    718
X146    704
X201    674
X329    671
X173    657
X092    653
X405    645
X190    640
X229    606
X254    604
X045    593
X253    593
X401    586
X219    575
X058    570
X041    562
X215    553
X050    537
X331    509
X072    489
X267    486
X164    486
X350    473
X203    463
X185    453
X042    448
X261    444
X281    440
X174    440
X138    437
X123    434
X347    419
X264    406
X133    402
X334    400
X026    391
X277    388
X247    383
X297    379
X260    369
X073    359
X252    353
X322    313
X139    296
X169    279
X265    269
X074    256
X241    256
X366    251
X392    241
X121    232
X317    231
X188    230
X155    224
X242    213
X341    205
X081    205
X217    200
X384    197
X413    197
X244    195
X107    191
X132    186
X332    183
X364    181
X308    177
X111    176
X122    165
X177    162
X435    158
X180    151
X199    150
X246    147
X444    142
X397    139
X270    130
X286    127
X135    124
X166    121
X324    121
X380    116
X083    106
X316    96
X320    92
X183    92
X458    92
X075    82
X196    81
X357    79
X205    77
X089    61
X161    60
X131    59
X202    54
X214    44
X061    43
X418    39
X119    28
X055    23
X437    20
X285    19
X269    19
X403    14
X432    11
X339    8
X359    5
X206    2
X211    1
Name: Plant, dtype: int64

In [107]:
plant_df["Plant"]

0      BC07
1      BC30
2      X001
3      X002
4      X003
5      X005
6      X006
7      X007
8      X008
9      X010
10     X011
11     X012
12     X013
13     X014
14     X016
15     X017
16     X018
17     X020
18     X021
19     X022
20     X023
21     X024
22     X025
23     X026
24     X027
25     X028
26     X029
27     X031
28     X032
29     X033
30     X034
31     X035
32     X036
33     X037
34     X039
35     X041
36     X042
37     X044
38     X045
39     X046
40     X047
41     X048
42     X049
43     X050
44     X051
45     X052
46     X053
47     X054
48     X055
49     X056
50     X057
51     X058
52     X060
53     X061
54     X062
55     X063
56     X064
57     X065
58     X066
59     X068
60     X072
61     X073
62     X074
63     X075
64     X076
65     X079
66     X080
67     X081
68     X082
69     X083
70     X084
71     X085
72     X086
73     X089
74     X091
75     X092
76     X095
77     X097
78     X098
79     X099
80     X101
81     X102
82     X103
83     X105
84     X106
85     X107
86     X108
87     X109
88     X110
89     X111
90     X112
91     X113
92     X114
93     X115
94     X118
95     X119
96     X121
97     X122
98     X123
99     X124
100    X125
101    X126
102    X127
103    X128
104    X129
105    X131
106    X132
107    X133
108    X135
109    X136
110    X138
111    X139
112    X140
113    X146
114    X147
115    X149
116    X150
117    X154
118    X155
119    X156
120    X157
121    X159
122    X160
123    X161
124    X164
125    X166
126    X167
127    X169
128    X170
129    X171
130    X172
131    X173
132    X174
133    X175
134    X177
135    X179
136    X180
137    X183
138    X185
139    X186
140    X187
141    X188
142    X190
143    X191
144    X192
145    X194
146    X196
147    X198
148    X199
149    X201
150    X202
151    X203
152    X204
153    X205
154    X206
155    X209
156    X210
157    X211
158    X213
159    X214
160    X215
161    X217
162    X218
163    X219
164    X224
165    X226
166    X227
167    X229
168    X231
169    X233
170    X238
171    X240
172    X241
173    X242
174    X243
175    X244
176    X245
177    X246
178    X247
179    X248
180    X249
181    X251
182    X252
183    X253
184    X254
185    X255
186    X256
187    X259
188    X260
189    X261
190    X262
191    X264
192    X265
193    X266
194    X267
195    X269
196    X270
197    X271
198    X276
199    X277
200    X278
201    X279
202    X281
203    X283
204    X285
205    X286
206    X287
207    X289
208    X291
209    X297
210    X298
211    X299
212    X300
213    X301
214    X302
215    X306
216    X307
217    X308
218    X310
219    X311
220    X312
221    X313
222    X316
223    X317
224    X318
225    X319
226    X320
227    X321
228    X322
229    X324
230    X326
231    X327
232    X328
233    X329
234    X330
235    X331
236    X332
237    X333
238    X334
239    X335
240    X339
241    X341
242    X342
243    X343
244    X344
245    X347
246    X349
247    X350
248    X351
249    X353
250    X357
251    X359
252    X360
253    X361
254    X363
255    X364
256    X366
257    X367
258    X368
259    X372
260    X374
261    X378
262    X380
263    X381
264    X384
265    X385
266    X386
267    X387
268    X389
269    X390
270    X391
271    X392
272    X393
273    X397
274    X398
275    X399
276    X400
277    X401
278    X402
279    X403
280    X404
281    X405
282    X406
283    X407
284    X408
285    X409
286    X410
287    X411
288    X413
289    X414
290    X416
291    X417
292    X418
293    X419
294    X421
295    X423
296    X424
297    X426
298    X428
299    X429
300    X431
301    X432
302    X433
303    X434
304    X435
305    X436
306    X437
307    X439
308    X440
309    X443
310    X444
311    X445
312    X447
313    X449
314    X450
315    X452
316    X453
317    X454
318    X456
319    X457
320    X458
321    X459
322    X460
323    X463
324    X464
325    X468
326    X472
327    X473
328    X474
329    X475
330    X478
331    X481
332    X483
333    X487
334    X490
335    X491
336    X492
337    X494
338    X498
339    X500
340    X501
341    X502
342    X504
343    X506
344    X507
345    X508
346    X511
347    X514
348    X515
349    X517
350    X521
351    X522
352    X523
353    X524
354    X526
355    X527
356    X529
357    X530
358    X531
359    X537
360    X538
361    X539
362    X542
363    X545
364    X548
365    X549
366    X551
367    X554
368    X555
369    X557
370    X563
371    X564
372    X565
373    X568
374    X569
375    X572
376    X575
377    X576
378    X577
379    X580
380    X581
381    X582
382    X585
383    X586
384    X588
385    X591
386    X593
387    X594
388    X595
389    X597
390    X600
391    X603
392    X604
393    X607
394    X621
395    X622
396    X624
397    X628
398    X630
399    X631
400    X633
401    X635
402    X636
403    X637
404    X639
405    X640
406    X644
407    X650
408    X655
409    X661
410    X672
411    X676
412    X677
413    X688
414    X689
415    X691
416    X693
417    X701
418    X704
419    X705
420    X706
421    X707
422    X709
423    X712
424    X714
425    X720
426    X728
427    X729
428    X748
429    X749
430    X756
431    X758
432    X770
433    X780
434    X781
435    X789
436    X795
437    X796
Name: Plant, dtype: object

In [112]:
#plants in inv_df but not in plant_df
inv_df[~inv_df['Plant'].isin(plant_df['Plant'])]['Plant'].value_counts()

BC03    28615
BC01    14483
BC05    13323
BC26    13253
BC06    12752
BC20    10259
BC08    10146
BC13    9990
BC23    9521
BC17    8631
BC15    8343
BC02    8209
BC28    8053
BC34    7483
BC31    6655
BC12    6577
BC16    5946
BC24    5888
BC19    5812
BC29    5244
BC25    5103
BC22    4911
BC33    4905
BC18    4873
BC04    4681
BC21    3506
BC32    3387
BC27    3347
BC11    2655
Name: Plant, dtype: int64

In [116]:
#Customers in cust_df but not in inv_df
cust_df[~cust_df['Customer No.'].isin(inv_df['Customer No.'])]['Customer No.'].value_counts()

1         1
379778    1
379792    1
379791    1
379790    1
         ..
190527    1
190526    1
190525    1
190524    1
E11584    1
Name: Customer No., Length: 551689, dtype: int64

In [119]:
#Customers in inv_df but not in cust_df
inv_df[~inv_df['Customer No.'].isin(cust_df['Customer No.'])]['Customer No.'].value_counts()

412       610
14505     441
221957    333
148721    145
56475     105
         ...
15930     1
218461    1
147329    1
187817    1
69369     1
Name: Customer No., Length: 249835, dtype: int64

In [115]:
cust_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000
...,...,...,...,...,...,...,...,...,...
555333,PLX506,PLX506,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000
555334,PLX507,PLX507,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000
555335,PLX508,PLX508,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000
555336,PLX555,PLX555,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000
555337,RSA100,RSA100,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000

In [120]:
cip_merge_df = pd.merge(pd.merge(cust_df,inv_df, on="Customer No.", how='outer'),plant_df, on="Plant", how="left")

In [121]:
cip_merge_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Unnamed: 0,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043998,NaN,203817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,984730.0,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,SWIFT,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043999,NaN,203808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,984734.0,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,RITZ,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044000,NaN,203844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,984735.0,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,XYLO,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044001,NaN,203820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,984736.0,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,ALTO,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044002,NaN,204288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,984740.0,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,WAGONR,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu

In [122]:
cip_merge_df.isnull().sum()

Business Partner           472587
Customer No.               0
Partner Type               472587
Data Origin                472587
Title                      472587
Marital Status             472587
Occupation                 472587
Date of Birth              472587
Death date                 472587
Unnamed: 0                 551689
Amt Rcvd From Custom       551689
Amt Rcvd From Ins Co       551689
Area / Locality            551689
CGST(14%)                  551689
CGST(2.5%)                 551689
CGST(6%)                   551689
CGST(9%)                   551689
CITY                       551689
Cash /Cashless Type        551689
Claim No.                  551689
Cust Type                  551689
District                   551689
Expiry Date                551689
Gate Pass Date             551689
Gate Pass Time             551689
IGST(12%)                  551689
IGST(18%)                  551689
IGST(28%)                  551689
IGST(5%)                   551689
Insurance Company          551689
Invoice Date               551689
Invoice No                 551689
Invoice Time               551689
Job Card No                551689
JobCard Date               551689
JobCard Time               551689
KMs Reading                551689
Labour Total               551689
Make                       551689
Misc Total                 551689
Model                      551689
ODN No.                    551689
OSL Total                  551689
Order Type                 551689
Outstanding Amt            551689
Parts Total                551689
Pin code                   551689
Plant                      551689
Plant Name1                551689
Policy no.                 551689
Print Status               551689
Recovrbl Exp               551689
Regn No                    551689
SGST/UGST(14%)             551689
SGST/UGST(2.5%)            551689
SGST/UGST(6%)              551689
SGST/UGST(9%)              551689
Service Advisor Name       551689
TDS amount                 551689
Technician Name            551689
Total Amt Wtd Tax.         551689
Total CGST                 551689
Total GST                  551689
Total IGST                 551689
Total SGST/UGST            551689
Total Value                551689
User ID                    551689
Name 1                     788240
Valuation Area             788240
Customer no. - plant       788240
Vendor number plant        788240
Factory calendar           788240
Name 2                     788240
House number and street    788240
PO Box                     788240
Postal Code                788240
City                       788240
Sales organization         788240
State                      788240
dtype: int64

In [123]:
cip_merge_df["Data Origin"].fillna(0, inplace=True) 
cip_merge_df["Partner Type"].fillna(0, inplace=True) 
cip_merge_df["Title"].fillna(0, inplace=True) 
cip_merge_df["Occupation"].fillna(0, inplace = True) 
cip_merge_df["Marital Status"].fillna(0, inplace=True) 

cip_merge_df["Date of Birth"].fillna('01-01-1900', inplace=True)
cip_merge_df["Death date"].fillna('31-12-3000', inplace=True)

In [124]:
cip_merge_df["Amt Rcvd From Custom"].fillna(0, inplace=True)
cip_merge_df["Amt Rcvd From Ins Co"].fillna(0, inplace=True)
cip_merge_df["CGST(14%)"].fillna(0, inplace=True)
cip_merge_df["CGST(2.5%)"].fillna(0, inplace=True)
cip_merge_df["CGST(6%)"].fillna(0, inplace=True)
cip_merge_df["CGST(9%)"].fillna(0, inplace=True)
cip_merge_df["IGST(12%)"].fillna(0, inplace=True)
cip_merge_df["IGST(18%)"].fillna(0, inplace=True)
cip_merge_df["IGST(28%)"].fillna(0, inplace=True)
cip_merge_df["IGST(5%)"].fillna(0, inplace=True)
cip_merge_df["SGST/UGST(14%)"].fillna(0, inplace=True)
cip_merge_df["SGST/UGST(2.5%)"].fillna(0, inplace=True)
cip_merge_df["SGST/UGST(6%)"].fillna(0, inplace=True)
cip_merge_df["SGST/UGST(9%)"].fillna(0, inplace=True)
cip_merge_df["Total CGST"].fillna(0, inplace=True)
cip_merge_df["Total GST"].fillna(0, inplace=True)
cip_merge_df["Total IGST"].fillna(0, inplace=True)
cip_merge_df["Total SGST/UGST"].fillna(0, inplace=True)
cip_merge_df["Total Value"].fillna(0, inplace=True)
cip_merge_df["Total Amt Wtd Tax."].fillna(0, inplace=True)
cip_merge_df["TDS amount"].fillna(0, inplace=True)
cip_merge_df["Recovrbl Exp"].fillna(0, inplace=True)
cip_merge_df["Outstanding Amt"].fillna(0, inplace=True)
cip_merge_df["Misc Total"].fillna(0, inplace=True)
cip_merge_df["Labour Total"].fillna(0, inplace=True)
cip_merge_df["KMs Reading"].fillna(0, inplace=True)
cip_merge_df["ODN No."].fillna(0, inplace=True)

cip_merge_df["Technician Name"].fillna('NotAvailable', inplace=True)
cip_merge_df["Service Advisor Name"].fillna('NotAvailable', inplace=True)
cip_merge_df["Policy no."].fillna('NotAvailable', inplace=True)
cip_merge_df["Model"].fillna('NotAvailable', inplace=True)
cip_merge_df["Insurance Company"].fillna('NotAvailable', inplace=True)
cip_merge_df["Area / Locality"].fillna('NotAvailable', inplace=True)
cip_merge_df["CITY"].fillna('NotAvailable', inplace=True)
cip_merge_df["Regn No"].fillna('NotAvailable', inplace=True)
cip_merge_df["Cash /Cashless Type"].fillna('NotAvailable', inplace=True)
cip_merge_df["Claim No."].fillna('NotAvailable', inplace=True)

cip_merge_df["Expiry Date"].fillna('31-12-3000', inplace=True)
cip_merge_df["Gate Pass Date"].fillna('31-12-3000', inplace=True)

In [125]:
cip_merge_df.drop('Unnamed: 0',axis=1, inplace=True)

In [126]:
cip_merge_df["Business Partner"].fillna('NotAvailable', inplace=True)
cip_merge_df["Cust Type"].fillna('NotAvailable', inplace=True)
cip_merge_df["District"].fillna('NotAvailable', inplace=True)
cip_merge_df["Make"].fillna('NotAvailable', inplace=True)
cip_merge_df["Order Type"].fillna('NotAvailable', inplace=True)
cip_merge_df["Plant"].fillna('NotAvailable', inplace=True)
cip_merge_df["Plant Name1"].fillna('NotAvailable', inplace=True)
cip_merge_df["Print Status"].fillna('NotAvailable', inplace=True)
cip_merge_df["User ID"].fillna('NotAvailable', inplace=True)
cip_merge_df["Order Type"].fillna('Not Available', inplace=True)

cip_merge_df["Invoice No"].fillna(0, inplace=True)
cip_merge_df["Job Card No"].fillna(0, inplace=True)
cip_merge_df["OSL Total"].fillna(0, inplace=True)
cip_merge_df["Parts Total"].fillna(0, inplace=True)
cip_merge_df["Pin code"].fillna(0, inplace=True)

cip_merge_df["Gate Pass Time"].fillna('00:00:00', inplace=True)
cip_merge_df["Invoice Time"].fillna('00:00:00', inplace=True)
cip_merge_df["JobCard Time"].fillna('00:00:00', inplace=True)

cip_merge_df["Invoice Date"].fillna('01-01-1900', inplace=True)
cip_merge_df["JobCard Date"].fillna('01-01-1900', inplace=True)

In [145]:
cip_merge_df["Name 1"].fillna('NotAvailable', inplace=True)
cip_merge_df["Valuation Area"].fillna('Not Available', inplace=True)
cip_merge_df["Factory calendar"].fillna('IN', inplace=True)
cip_merge_df["Name 2"].fillna('Not Available', inplace=True)
cip_merge_df["House number and street"].fillna('Not Available', inplace=True)
cip_merge_df["City"].fillna('Not Available', inplace=True)
cip_merge_df["Sales organization"].fillna('Not Available', inplace=True)
cip_merge_df["State"].fillna('Not Available', inplace=True)

cip_merge_df["PO Box"].fillna(0, inplace=True)
cip_merge_df["Postal Code"].fillna(0, inplace=True)

cip_merge_df["Customer no. - plant"].fillna('Not Available', inplace=True)
cip_merge_df["Vendor number plant"].fillna('Not Available', inplace=True)

In [146]:
cip_merge_df.isnull().sum()

Business Partner           0
Customer No.               0
Partner Type               0
Data Origin                0
Title                      0
Marital Status             0
Occupation                 0
Date of Birth              0
Death date                 0
Amt Rcvd From Custom       0
Amt Rcvd From Ins Co       0
Area / Locality            0
CGST(14%)                  0
CGST(2.5%)                 0
CGST(6%)                   0
CGST(9%)                   0
CITY                       0
Cash /Cashless Type        0
Claim No.                  0
Cust Type                  0
District                   0
Expiry Date                0
Gate Pass Date             0
Gate Pass Time             0
IGST(12%)                  0
IGST(18%)                  0
IGST(28%)                  0
IGST(5%)                   0
Insurance Company          0
Invoice Date               0
Invoice No                 0
Invoice Time               0
Job Card No                0
JobCard Date               0
JobCard Time               0
KMs Reading                0
Labour Total               0
Make                       0
Misc Total                 0
Model                      0
ODN No.                    0
OSL Total                  0
Order Type                 0
Outstanding Amt            0
Parts Total                0
Pin code                   0
Plant                      0
Plant Name1                0
Policy no.                 0
Print Status               0
Recovrbl Exp               0
Regn No                    0
SGST/UGST(14%)             0
SGST/UGST(2.5%)            0
SGST/UGST(6%)              0
SGST/UGST(9%)              0
Service Advisor Name       0
TDS amount                 0
Technician Name            0
Total Amt Wtd Tax.         0
Total CGST                 0
Total GST                  0
Total IGST                 0
Total SGST/UGST            0
Total Value                0
User ID                    0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        0
Factory calendar           0
Name 2                     0
House number and street    0
PO Box                     0
Postal Code                0
City                       0
Sales organization         0
State                      0
dtype: int64

In [147]:
cip_merge_df[~cip_merge_df['Customer no. - plant'].isnull()]

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043998,NotAvailable,203817,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,SWIFT,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043999,NotAvailable,203808,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,RITZ,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044000,NotAvailable,203844,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,XYLO,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044001,NotAvailable,203820,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,ALTO,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044002,NotAvailable,204288,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,WAGONR,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu

In [138]:
cip_merge_df.tail(10)

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State
1043993,NotAvailable,203807,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NEW AVADI RD,0.0,0.0,0.0,0.0,"KILPAUK, CHENNAI",NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,10:37:11,400073.0,2016-06-30,07:50:19,13409.0,864.45,NISSAN,245.98,SUPER SUNNY,0,0.0,Paid Service,0.0,812.22,600010.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT5168,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1922.65,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043994,NotAvailable,203819,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,AYANAVARAM,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,11:47:57,400094.0,2016-06-30,08:52:54,29191.0,147.80,MARUTI SUZUKI,0.00,SWIFT DZIRE,0,0.0,Running Repairs,0.0,0.00,600023.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN09BV3132,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,147.80,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043995,NotAvailable,203816,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"KOTTUR,",0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,11:48:19,400079.0,2016-06-30,08:27:19,50495.0,147.80,MARUTI SUZUKI,0.00,SWIFT DZIRE,0,0.0,Running Repairs,0.0,0.00,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22CT9609,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,147.80,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043996,NotAvailable,203810,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,11:48:55,400076.0,2016-06-30,08:15:55,102292.0,147.80,TATA MOTORS,0.00,INDIGO,0,0.0,Running Repairs,0.0,0.00,600054.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,AP09BR5488,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,147.80,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043997,NotAvailable,203818,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Tambaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:00,400091.0,2016-06-30,08:39:55,78217.0,631.24,MAHINDRA & MAHINDRA,0.00,QUANTO,0,0.0,Running Repairs,0.0,668.19,600045.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN09BR0022,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1299.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043998,NotAvailable,203817,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,SWIFT,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1043999,NotAvailable,203808,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,RITZ,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044000,NotAvailable,203844,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,XYLO,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044001,NotAvailable,203820,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,ALTO,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu
1044002,NotAvailable,204288,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,WAGONR,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu

In [148]:
cip_merge_df[cip_merge_df['City'].isnull()]["CITY"].value_counts()

Series([], Name: CITY, dtype: int64)

In [63]:
#cip_df=pd.merge(pd.merge(cust_df,inv_df, on="Customer No.", how="left"),plant_df, on="Plant", how="left")

In [64]:
cip_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Unnamed: 0,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571411,PLX506,PLX506,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571412,PLX507,PLX507,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571413,PLX508,PLX508,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571414,PLX555,PLX555,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
571415,RSA100,RSA100,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
#cip_df.to_csv("../data/cip.csv")

In [149]:
#cip_merge_df.to_csv("../data/cip_merge.csv")

In [150]:
def rearrange_target(df,target):
    return (pd.concat([df.drop(target,axis=1),df[target]],axis=1))

In [151]:
#Problem Statement 1 - Dataframe with Model as target variable
df1_Xy = rearrange_target(cip_merge_df,"Model")

In [152]:
#Problem Statement 2 - Dataframe with Order Type as target variable
df2_Xy = rearrange_target(cip_merge_df,"Order Type")

In [153]:
df1_Xy

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State,Model
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NotAvailable
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NotAvailable
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NotAvailable
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NotAvailable
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NotAvailable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043998,NotAvailable,203817,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,SWIFT
1043999,NotAvailable,203808,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,RITZ
1044000,NotAvailable,203844,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,XYLO
1044001,NotAvailable,203820,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,ALTO
1044002,NotAvailable,204288,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,WAGONR

In [30]:
df2_Xy

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Unnamed: 0,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State,Order Type
0,CS000018,CS000018,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,787293,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Chengalpattu,NotAvailable,NotAvailable,Retail,Tamil Nadu,2016-08-18 00:00:00,2016-04-28 00:00:00,15:34:30,0.0,0.0,0.0,0.0,UNIVERSAL SOMPO GENERAL INSURANCE C,2016-04-28,7011203471,15:30:01,350079,2016-04-09,20:04:37,3000,0.00,HONDA,49.75,MOBILIO,0,0.00,0.0,0.00,603204,BC07,NERKUNDRAM,M4586523,YES,0.0,TN19Q2153,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,49.75,0.0,0.0,0.0,0.0,0.00,BC07SA2,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,Chennai,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu,Mechanical
1,E10023,E10023,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,101261,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Hyderabad,NotAvailable,NotAvailable,Retail,Andhra Pradesh,31-12-3000,2015-11-23 00:00:00,15:32:39,0.0,0.0,0.0,0.0,NotAvailable,2015-11-23,7011202377,15:08:47,281962,2015-11-22,11:00:32,35760,0.00,HYUNDAI,149.39,SANTRO,7011202377.0,0.00,0.0,0.00,500012,BC07,NERKUNDRAM,NotAvailable,YES,0.0,TN07BB9491,0.0,0.0,0.0,0.0,NotAvailable,0.0,sdfhghgh,149.39,0.0,0.0,0.0,0.0,149.39,BC07SA2,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,Chennai,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu,Running Repairs
2,E10381,E10381,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,90457,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,2015-10-20 00:00:00,18:29:18,0.0,0.0,0.0,0.0,NotAvailable,2015-10-20,7011202184,18:27:38,270612,2015-10-20,12:02:10,84950,179.97,TATA MOTORS,86.98,INDICA,7011202184.0,1149.74,0.0,392.94,600040,BC07,NERKUNDRAM,NotAvailable,YES,0.0,TN01AA2382,0.0,0.0,0.0,0.0,NotAvailable,0.0,ARUN,1809.63,0.0,0.0,0.0,0.0,1809.63,BC07SA2,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,Chennai,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu,Running Repairs
3,E10381,E10381,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,623411,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2014-08-30,7000141077,11:46:03,140864,2014-08-27,09:30:20,81591,0.00,TATA MOTORS,50.02,INDICA,7000141077.0,699.33,0.0,118.85,600040,BC07,NERKUNDRAM,NotAvailable,NO,0.0,TN01AA2382,0.0,0.0,0.0,0.0,NotAvailable,0.0,MAHA,868.20,0.0,0.0,0.0,0.0,868.20,BC07SA1,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,Chennai,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu,Running Repairs
4,E10381,E10381,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,624463,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2014-09-03,7000142183,17:25:01,142546,2014-09-03,15:54:17,81601,0.00,TATA MOTORS,0.00,INDICA,7000142183.0,0.00,0.0,0.00,600040,BC07,NERKUNDRAM,NotAvailable,NO,0.0,TN01AA2382,0.0,0.0,0.0,0.0,NotAvailable,0.0,SATHISH,0.00,0.0,0.0,0.0,0.0,0.00,BC07SA1,NERKUNDRAM,BC07,PLBC07,PLBC07,IN,Chennai,"No.117 Poonamallee High Road,",600107.0,600107,Chennai,MFCS,Tamil Nadu,Running Repairs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129,PLX076,PLX076,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,879507,0.0,0.0,X076,0.0,0.0,0.0,0.0,Firozabad,NotAvailable,NotAvailable,Franchise,Uttar Pradesh,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-09-30,7165201046,18:57:36,473186,2016-09-30,18:27:10,79500,3691.27,HONDA,219.97,AMAZE,0,0.00,0.0,0.00,283203,X076,X076 - CAR X CARE,NotAvailable,NO,0.0,UP83AA2201,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,3911.24,0.0,0.0,0.0,0.0,0.00,X076WM1,X076 - CAR X CARE,X076,PLX076,NotAvailable,IN,Firozabad,"Chameli Bagh, Near Raja Ka Taa",283203.0,283203,Firozabad,MFCD,Uttar Pradesh,Running Repairs
2130,PLX081,PLX081,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,901757,0.0,0.0,X081,0.0,0.0,0.0,0.0,KOTTAYAM,NotAvailable,NotAvailable,Franchise,Kerala,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-10-25,7216400159,17:42:59,494621,2016-10-25,14:46:38,148024,1458.08,MITSUBISHI MOTORS,0.00,PAJERO,0,0.00,0.0,2112.00,686013,X332,X332 - KAINIKKARA MOTORS,NotAvailable,NO,0.0,KL01AQ5050,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,3570.08,0.0,0.0,0.0,0.0,0.00,X332SA1,X332 - KAINIKKARA MOTORS,X332,PLX332,NotAvailable,IN,Kotayyam,"NP/XI/216D , Nattakkom,",686013.0,689653,Kotayyam,MFCD,Kerala,Paid Service
2131,PLX241,PLX241,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,891378,0.0,0.0,X241,0.0,0.0,0.0,0.0,Kashipur,NotAvailable,NotAvailable,Franchise,Uttarakhand,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-10-14,7198200103,14:49:55,483985,2016-10-14,14:36:29,56328,3257.38,MARUTI SUZUKI,219.99,RITZ,0,0.00,0.0,0.00,244713,X241,X241 - SHRI KRISHNA AUTOMOTIVE,NotAvailable,NO,0.0,MH43AJ8324,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,3477.37,0.0,0.0,0.0,0.0,0.00,X241WM1,X241 - SHRI KRISHNA AUTOMOTIVE,X241,PLX241,NotAvailable,IN,Kashipur,"Khasra No. 87, Kashipur Ramnag",244713.0,244713,Kashipur,MFCD,Uttarakhand,Running Repairs
2132,PLX277,PLX277,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,905801,0.0,0.0,X277,0.0,0.0,0.0,0.0,Jalpaiguri,NotAvailable,NotAvailable,Retail,West Bengal,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-10-26,7205400355,19:51:17,493813,2016-10-24,18:18:15,52358,1245.04,TATA MOTORS,0.00,SUMO,0,0.00,0.0,5625.91,735121,X277,X277 - BRISTI AUTOMOBILES,NotAvailable,NO,0.0,WB72G6072,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,6870.95,0.0,0.0,0.0,0.0,0.00,X277SA1,X277 - BRISTI AUTOMOBILES,X277,PLX277,NotAvailable,IN,Jalpaiguri,"Ghasi Para, Paharpur,",735121.0,735121,Jalpaiguri,MFCD,West Bengal,Running Repairs
2133,PLX380,PLX380,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,881446,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,Meerut,NotAvailable,NotAvailable,Retail,Uttar Pradesh,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-09-30,7226000014,18:32:09,473182,2016-09-30,18:13:47,90704,4126.97,MAHINDRA & MAHINDRA,220.01,XUV 500,0,0.00,0.0,0.00,250103,X380,X380 - A2Z AUTOWORLD,NotAvailable,NO,0.0,UP15BF6060,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4346.98,0.0,0.0,0.0,0.0,0.00,X380SA1,X380 - A2Z AUTOWORLD,X380,PLX380,NotAvailable,IN,Meerut,"NH-58, Khasra no - 463,",250103.0,250103,Meerut,MFCD,Uttar Pradesh,Running Repairs

# Load Additional datasets

In [31]:
car_price_df = pd.read_excel('../data/AdditionalDatasets/MakeModelPrice.xlsx')

In [155]:
car_price_df

                     Make                   Model  PriceLow  PriceHigh
0    AUDI                  A4                      42.34     46.67
1    AUDI                  A6                      55.96     60.59
2    AUDI                  A7                      90.50     90.50
3    AUDI                  A8                      156.00    216.00
4    AUDI                  Q5                      50.27     56.26
5    AUDI                  Q7                      69.22     86.30
6    AUDI                  TT                      82.07     82.07
7    BMW                   3 SERIES                43.60     62.90
8    BMW                   5 SERIES                56.00     69.10
9    BMW                   6 SERIES                67.90     77.90
10   BMW                   7 SERIES                137.00    246.00
11   BMW                   BMW X6                  115.00    167.00
12   BMW                   BMW-M3                  125.00    130.00
13   BMW                   BMW-M5                  155.00    181.00
14   BMW                   BMW-M6                  214.00    222.00
15   BMW                   MINIS                   47.12     51.72
16   BMW                   X1                      38.50     42.90
17   BMW                   X3                      56.50     63.70
18   BMW                   X5                      76.50     88.00
19   BMW                   Z4                      67.00     81.90
20   DAEWOO                CIELO                   5.46      6.05
21   DAEWOO                MATIZ                   3.05      4.15
22   DAEWOO                NEXIA                   6.22      6.59
23   FIAT                  500                     14.83     14.93
24   FIAT                  ADVENTURE               5.53      5.65
25   FIAT                  GRAND PUNTO             4.75      7.60
26   FIAT                  LINEA                   7.19      10.79
27   FIAT                  PALIO                   3.41      3.58
28   FIAT                  PALIO STILE             3.90      4.31
29   FIAT                  PETRA                   2.44      2.66
30   FIAT                  SIENA                   5.25      5.25
31   FIAT                  UNO                     2.55      3.95
32   FORCE                 FORCE ONE               8.72      13.17
33   FORCE                 TRAX                    6.86      7.03
34   FORD                  ECOSPORT                8.19      11.69
35   FORD                  ENDEAVOUR               29.99     36.25
36   FORD                  ESCORT                  7.05      7.05
37   FORD                  FIESTA                  5.44      8.50
38   FORD                  FIGO                    5.82      8.37
39   FORD                  FOCUS                   9.00      9.00
40   FORD                  FUSION                  5.94      6.83
41   FORD                  IKON                    4.82      5.25
42   FORD                  LIMOUSINE               40.00     40.00
43   FORD                  MONDEO                  8.13      8.68
44   GENERAL MOTORS        AVEO                    5.98      7.42
45   GENERAL MOTORS        AVEO UV-A               4.07      5.01
46   GENERAL MOTORS        BEAT                    3.96      6.04
47   GENERAL MOTORS        CAPTIVA                 25.13     27.36
48   GENERAL MOTORS        CHEVROLET CRUZE         13.38     16.65
49   GENERAL MOTORS        ENJOY                   4.99      6.52
50   GENERAL MOTORS        FORESTER                10.00     10.00
51   GENERAL MOTORS        OPEL ASTRA              7.55      7.55
52   GENERAL MOTORS        OPEL CORSA              4.75      4.75
53   GENERAL MOTORS        OPTRA                   8.17      11.83
54   GENERAL MOTORS        OPTRA MAGNUM            7.41      9.55
55   GENERAL MOTORS        SAIL                    5.30      6.83
56   GENERAL MOTORS        SPARK                   3.67      4.39
57   GENERAL MOTORS        SRV                     6.98      6.98
58   GENERAL MOTORS        TAVERA                  6.48      11.68
59   GENERAL MOTORS        TAVERA NEO              6.82      10.11
60   GENERAL MOTORS        TRAILBLAZER             24.36     29.98
61   GENERAL MOTORS        VECTRA                  16.75     16.75
62   HINDUSTAN MOTORS      AMBASSADOR              4.54      7.15
63   HINDUSTAN MOTORS      AVIGO                   5.42      5.42
64   HINDUSTAN MOTORS      CONTESSA                4.83      4.83
65   HINDUSTAN MOTORS      GRAND                   5.95      5.95
66   HINDUSTAN MOTORS      PUSHPAK                 3.49      3.49
67   HINDUSTAN MOTORS      TREKKER                 4.98      4.98
68   HONDA                 ACCORD                  43.21     44.28
69   HONDA                 AMAZE                   6.31      9.99
70   HONDA                 BRIO                    4.60      7.84
71   HONDA                 BRV                     9.53      13.83
72   HONDA                 CITY                    9.29      15.05
73   HONDA                 CIVIC                   17.95     22.36
74   HONDA                 CR-V                    28.34     32.84
75   HONDA                 JAZZ                    7.73      9.98
76   HONDA                 MOBILIO                 7.17      12.32
77   HYUNDAI               ACCENT                  4.50      7.49
78   HYUNDAI               CRETA                   9.99      17.67
79   HYUNDAI               ELANTRA                 17.85     17.85
80   HYUNDAI               EON                     3.33      4.67
81   HYUNDAI               GETZ                    3.59      4.77
82   HYUNDAI               I10                     4.36      5.17
83   HYUNDAI               I20                     5.54      9.10
84   HYUNDAI               SANTA FE                27.87     36.36
85   HYUNDAI               SANTRO                  4.73      6.41
86   HYUNDAI               SANTRO XING             3.18      5.12
87   HYUNDAI               SONATA                  19.20     20.77
88   HYUNDAI               SONATA V-6              20.77     20.77
89   HYUNDAI               TERRACAN                19.48     25.00
90   HYUNDAI               TUCSON                  22.57     22.57
91   HYUNDAI               VELOSTER                15.00     23.22
92   HYUNDAI               VERNA                   9.20      15.26
93   HYUNDAI               XCENT                   5.81      7.86
94   JEEP                  CHEROKEE                75.15     114.00
95   LAND ROVER            ROVER                   75.59     211.00
96   MAHINDRA &  MAHINDRA  ARMADA                  6.50      7.30
97   MAHINDRA &  MAHINDRA  BOLERO                  8.40      9.39
98   MAHINDRA &  MAHINDRA  BOLERO PIK UP           8.09      8.35
99   MAHINDRA &  MAHINDRA  CLASSIC                 5.50      6.47
100  MAHINDRA &  MAHINDRA  COMMANDER               6.10      6.10
101  MAHINDRA &  MAHINDRA  GENIO                   5.99      6.48
102  MAHINDRA &  MAHINDRA  KUV100                  4.42      6.76
103  MAHINDRA &  MAHINDRA  LOGAN D                 4.66      6.38
104  MAHINDRA &  MAHINDRA  LOGAN P                 4.66      6.38
105  MAHINDRA &  MAHINDRA  MAHINDRA LOGAN CNG      4.50      4.50
106  MAHINDRA &  MAHINDRA  MAHINDRA MM             5.53      5.53
107  MAHINDRA &  MAHINDRA  MAHINDRA PIK UP         8.09      8.35
108  MAHINDRA &  MAHINDRA  MARSHAL                 5.99      6.50
109  MAHINDRA &  MAHINDRA  MAXX                    7.99      7.99
110  MAHINDRA &  MAHINDRA  MAXXIMO                 4.22      4.22
111  MAHINDRA &  MAHINDRA  QUANTO                  6.77      8.65
112  MAHINDRA &  MAHINDRA  REVA                    4.99      6.14
113  MAHINDRA &  MAHINDRA  SCORPIO CRDE            12.31     17.02
114  MAHINDRA &  MAHINDRA  SCORPIO NEF             12.32     17.07
115  MAHINDRA &  MAHINDRA  SSANYONG KORANDO        15.00     15.00
116  MAHINDRA &  MAHINDRA  SSANYONG REXTON         20.57     25.22
117  MAHINDRA &  MAHINDRA  SUPRO                   5.29      7.39
118  MAHINDRA &  MAHINDRA  THAR                    12.11     14.96
119  MAHINDRA &  MAHINDRA  TUV300                  8.59      10.61
120  MAHINDRA &  MAHINDRA  VERITO                  5.28      7.23
121  MAHINDRA &  MAHINDRA  XUV 500                 15.13     20.03
122  MAHINDRA &  MAHINDRA  XYLO                    8.86      12.13
123  MARUTI SUZUKI         800                     2.99      4.60
124  MARUTI SUZUKI         A STAR                  3.71      4.57
125  MARUTI SUZUKI         ALTO                    2.99      4.60
126  MARUTI SUZUKI         BALENO                  5.98      9.30
127  MARUTI SUZUKI         BREZZA                  7.51      11.41
128  MARUTI SUZUKI         CELERIO                 4.65      5.90
129  MARUTI SUZUKI         CIAZ                    8.52      11.50
130  MARUTI SUZUKI         EECO                    4.08      5.29
131  MARUTI SUZUKI         ERTIGA                  7.81      10.59
132  MARUTI SUZUKI         ESTEEM 1000             4.63      6.15
133  MARUTI SUZUKI         ESTEEM 1300             4.63      6.15
134  MARUTI SUZUKI         ESTILO                  3.19      4.25
135  MARUTI SUZUKI         GRAND VITARA            7.51      11.41
136  MARUTI SUZUKI         GYPSY 1000              5.71      6.37
137  MARUTI SUZUKI         GYPSY 1300              6.23      6.37
138  MARUTI SUZUKI         KIZASHI                 16.53     18.21
139  MARUTI SUZUKI         OMNI                    2.75      3.33
140  MARUTI SUZUKI         RITZ                    4.45      6.81
141  MARUTI SUZUKI         SWIFT                   5.73      8.41
142  MARUTI SUZUKI         SWIFT DZIRE             5.98      9.02
143  MARUTI SUZUKI         SX4                     7.72      10.30
144  MARUTI SUZUKI         VERSA                   3.67      4.78
145  MARUTI SUZUKI         WAGONR                  4.79      6.32
146  MARUTI SUZUKI         ZEN                     3.40      4.14
147  MARUTI SUZUKI         ZEN ESTILO              3.19      4.25
148  MERCEDES BENZ         C-CLASS                 41.31     139.00
149  MERCEDES BENZ         CL-CLASS                119.00    119.00
150  MERCEDES BENZ         CLK-CLASS               84.32     84.32
151  MERCEDES BENZ         CLS-CLASS               86.39     86.39
152  MERCEDES BENZ         E-CLASS                 63.60     80.90
153  MERCEDES BENZ         G CLASS                 162.00    242.00
154  MERCEDES BENZ         GL-CLASS                79.78     179.00
155  MERCEDES BENZ         ML 350                  52.19     66.97
156  MERCEDES BENZ         ML-CLASS                56.74     66.97
157  MERCEDES BENZ         S 320 CDI L             80.25     80.25
158  MERCEDES BENZ         S 350 L                 142.00    142.00
159  MERCEDES BENZ         S-CLASS                 141.00    278.00
160  MERCEDES BENZ         SL-CLASS                100.00    115.00
161  MERCEDES BENZ         SLK-CLASS               47.58     87.66
162  MITSUBISHI MOTORS     CEDIA                   8.24      9.80
163  MITSUBISHI MOTORS     LANCER                  7.33      8.13
164  MITSUBISHI MOTORS     MONTERO                 41.34     67.88
165  MITSUBISHI MOTORS     OUTLANDER               20.25     26.93
166  MITSUBISHI MOTORS     PAJERO                  18.81     23.91
167  MORRIS                AUSTIN                  12.18     16.88
168  NISSAN                DATSUN GO               4.03      6.51
169  NISSAN                EVALIA                  9.53      12.75
170  NISSAN                LAUREL                  9.82      10.70
171  NISSAN                MICRA                   6.10      8.13
172  NISSAN                SUPER SUNNY             7.07      10.89
173  NISSAN                TEANA                   21.14     24.89
174  NISSAN                TERRANO                 9.99      14.20
175  NISSAN                X-TRAIL                 22.77     25.87
176  PORCHE                CAYENNE                 120.00    192.00
177  PORCHE                CAYMAN S                85.46     94.51
178  PREMIERÂ AUTOMOBILES  PADMINI                 2.12      2.12
179  PREMIERÂ AUTOMOBILES  RIO                     5.25      7.24
180  RENAULT               DUSTER                  10.49     13.59
181  RENAULT               FLUENCE                 14.72     16.30
182  RENAULT               KOLEOS                  23.47     27.74
183  RENAULT               KWID                    3.18      5.39
184  RENAULT               LODGY                   8.84      12.83
185  RENAULT               PULSE                   4.46      6.92
186  RENAULT               RENAULT 1.9             5.30      7.82
187  RENAULT               SCALA                   8.20      9.72
188  SAN MOTORS            SAN STORM 1.2           5.75      6.89
189  SKODA                 FABIA                   7.00      9.00
190  SKODA                 LAURA                   12.92     17.98
191  SKODA                 OCTAVIA                 20.00     35.99
192  SKODA                 RAPID                   7.79      13.29
193  SKODA                 ROOMSTER                14.00     14.00
194  SKODA                 SUPERB                  31.99     34.99
195  SKODA                 YETI                    20.11     23.34
196  SONALIKA              RHINO RX                6.45      8.17
197  TATA MOTORS           207                     6.06      6.06
198  TATA MOTORS           ACE                     4.41      5.14
199  TATA MOTORS           ARIA                    10.41     16.02
200  TATA MOTORS           BOLT                    4.71      7.88
201  TATA MOTORS           INDICA                  3.78      5.22
202  TATA MOTORS           INDIGO                  4.85      6.28
203  TATA MOTORS           INDIGO MANZA            5.86      7.94
204  TATA MOTORS           INDIGO MARINA           4.23      6.31
205  TATA MOTORS           JAGUAR XF               54.36     60.73
206  TATA MOTORS           JAGUAR XJ               96.37     145.00
207  TATA MOTORS           JAGUAR XL               99.56     99.56
208  TATA MOTORS           LAND ROVER DISCOVERY    75.59     87.99
209  TATA MOTORS           LAND ROVER FREELANDER   38.67     43.92
210  TATA MOTORS           LAND ROVER RANGE ROVER  182.00    419.00
211  TATA MOTORS           MAGIC                   5.19      5.19
212  TATA MOTORS           NANO                    1.10      2.36
213  TATA MOTORS           SAFARI                  14.99     21.81
214  TATA MOTORS           SIERRA                  10.00     14.00
215  TATA MOTORS           SUMO                    6.29      8.68
216  TATA MOTORS           SUMO GRANDE             7.65      9.27
217  TATA MOTORS           TIAGO                   4.99      6.95
218  TATA MOTORS           VENTURE                 4.37      5.86
219  TATA MOTORS           VISTA                   4.10      6.82
220  TATA MOTORS           WINGER                  7.48      12.05
221  TATA MOTORS           XENON XT                9.96      12.90
222  TATA MOTORS           ZEST                    5.82      9.18
223  TOYOTA                CAMRY                   37.88     47.16
224  TOYOTA                COROLLA                 9.01      12.39
225  TOYOTA                COROLLA ALTIS           16.46     20.20
226  TOYOTA                ETIOS                   5.68      7.85
227  TOYOTA                FORTUNER                30.34     38.30
228  TOYOTA                INNOVA                  16.52     24.59
229  TOYOTA                LAND CRUISER PRADO      84.87     120.00
230  TOYOTA                QUALIS                  7.34      7.89
231  VOLKSWAGEN            AMEO                    5.67      7.99
232  VOLKSWAGEN            JETTA                   14.78     20.89
233  VOLKSWAGEN            PASSAT                  25.99     33.21
234  VOLKSWAGEN            POLO                    6.16      9.99
235  VOLKSWAGEN            TOUAREG                 55.18     82.00
236  VOLKSWAGEN            VENTO                   8.69      13.83
237  VOLVO                 VOLVO S80               34.07     46.20
238  VOLVO                 VOLVO XC90              80.90     131.00

In [156]:
cip_df["Model"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
571411    NaN
571412    NaN
571413    NaN
571414    NaN
571415    NaN
Name: Model, Length: 571416, dtype: object

In [157]:
cip2_df = pd.merge(cip_merge_df,car_price_df, how='left', on=['Model','Make'])

In [158]:
cip2_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State,PriceLow,PriceHigh
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NaN,NaN
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NaN,NaN
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NaN,NaN
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NaN,NaN
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043998,NotAvailable,203817,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,SWIFT,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,5.73,8.41
1043999,NotAvailable,203808,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,RITZ,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,4.45,6.81
1044000,NotAvailable,203844,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,XYLO,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,8.86,12.13
1044001,NotAvailable,203820,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,ALTO,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,2.99,4.60
1044002,NotAvailable,204288,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,WAGONR,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,4.79,6.32

In [159]:
cip2_df.isnull().sum()

Business Partner           0
Customer No.               0
Partner Type               0
Data Origin                0
Title                      0
Marital Status             0
Occupation                 0
Date of Birth              0
Death date                 0
Amt Rcvd From Custom       0
Amt Rcvd From Ins Co       0
Area / Locality            0
CGST(14%)                  0
CGST(2.5%)                 0
CGST(6%)                   0
CGST(9%)                   0
CITY                       0
Cash /Cashless Type        0
Claim No.                  0
Cust Type                  0
District                   0
Expiry Date                0
Gate Pass Date             0
Gate Pass Time             0
IGST(12%)                  0
IGST(18%)                  0
IGST(28%)                  0
IGST(5%)                   0
Insurance Company          0
Invoice Date               0
Invoice No                 0
Invoice Time               0
Job Card No                0
JobCard Date               0
JobCard Time               0
KMs Reading                0
Labour Total               0
Make                       0
Misc Total                 0
Model                      0
ODN No.                    0
OSL Total                  0
Order Type                 0
Outstanding Amt            0
Parts Total                0
Pin code                   0
Plant                      0
Plant Name1                0
Policy no.                 0
Print Status               0
Recovrbl Exp               0
Regn No                    0
SGST/UGST(14%)             0
SGST/UGST(2.5%)            0
SGST/UGST(6%)              0
SGST/UGST(9%)              0
Service Advisor Name       0
TDS amount                 0
Technician Name            0
Total Amt Wtd Tax.         0
Total CGST                 0
Total GST                  0
Total IGST                 0
Total SGST/UGST            0
Total Value                0
User ID                    0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        0
Factory calendar           0
Name 2                     0
House number and street    0
PO Box                     0
Postal Code                0
City                       0
Sales organization         0
State                      0
PriceLow                   553648
PriceHigh                  553648
dtype: int64

In [162]:
cip2_df[cip2_df["PriceLow"].isnull()][["Make","Model"]].value_counts()

Make                  Model
NotAvailable          NotAvailable    551689
MARUTI SUZUKI         NotAvailable    477
MAHINDRA &  MAHINDRA  NotAvailable    324
GENERAL MOTORS        OPEL            232
HYUNDAI               NotAvailable    230
TATA MOTORS           NotAvailable    166
GENERAL MOTORS        NotAvailable    88
PREMIER AUTOMOBILES   RIO             78
MAHINDRA &  MAHINDRA  MAHINDRA CNG    73
FORD                  NotAvailable    70
HONDA                 NotAvailable    48
TOYOTA                NotAvailable    47
FIAT                  NotAvailable    36
VOLKSWAGEN            NotAvailable    18
PREMIER AUTOMOBILES   PADMINI         15
SKODA                 NotAvailable    15
TATA MOTORS           TL              14
MARUTI SUZUKI         SWIFT D,ZIRE    8
HYUNDAI               ALTO            5
HONDA                 SAIL            4
NISSAN                NotAvailable    3
MARUTI SUZUKI         ASTAR           2
RENAULT               NotAvailable    2
TOYOTA                TATA-NANO       2
FORD                  ECO SPORT       1
BMW                   NotAvailable    1
dtype: int64

In [163]:
cip2_df['PriceLow'].fillna(0, inplace=True)
cip2_df['PriceHigh'].fillna(0, inplace=True)

In [164]:
cip2_df.isnull().sum()

Business Partner           0
Customer No.               0
Partner Type               0
Data Origin                0
Title                      0
Marital Status             0
Occupation                 0
Date of Birth              0
Death date                 0
Amt Rcvd From Custom       0
Amt Rcvd From Ins Co       0
Area / Locality            0
CGST(14%)                  0
CGST(2.5%)                 0
CGST(6%)                   0
CGST(9%)                   0
CITY                       0
Cash /Cashless Type        0
Claim No.                  0
Cust Type                  0
District                   0
Expiry Date                0
Gate Pass Date             0
Gate Pass Time             0
IGST(12%)                  0
IGST(18%)                  0
IGST(28%)                  0
IGST(5%)                   0
Insurance Company          0
Invoice Date               0
Invoice No                 0
Invoice Time               0
Job Card No                0
JobCard Date               0
JobCard Time               0
KMs Reading                0
Labour Total               0
Make                       0
Misc Total                 0
Model                      0
ODN No.                    0
OSL Total                  0
Order Type                 0
Outstanding Amt            0
Parts Total                0
Pin code                   0
Plant                      0
Plant Name1                0
Policy no.                 0
Print Status               0
Recovrbl Exp               0
Regn No                    0
SGST/UGST(14%)             0
SGST/UGST(2.5%)            0
SGST/UGST(6%)              0
SGST/UGST(9%)              0
Service Advisor Name       0
TDS amount                 0
Technician Name            0
Total Amt Wtd Tax.         0
Total CGST                 0
Total GST                  0
Total IGST                 0
Total SGST/UGST            0
Total Value                0
User ID                    0
Name 1                     0
Valuation Area             0
Customer no. - plant       0
Vendor number plant        0
Factory calendar           0
Name 2                     0
House number and street    0
PO Box                     0
Postal Code                0
City                       0
Sales organization         0
State                      0
PriceLow                   0
PriceHigh                  0
dtype: int64

In [165]:
cip2_df["City"].value_counts()

Not Available      788240
Chennai            21675
Coimbatore         9371
Bengaluru          7649
Mohali             7403
Thane              7388
Madurai            6459
Pune               6092
Mangalore          5928
Moga               5497
Neyveli            4971
Aurangabad         4816
Chidambaram        4427
Thanjavur          4079
Ambur              3639
Mysore             3610
Kolhapur           3328
Bhopal             3326
Zirakpur           3284
Shimoga            3264
Salem              3107
Tiruchirappalli    3022
Tirupur            2857
Chomu              2831
Hyderabad          2804
Nashik             2786
Tirunelveli        2756
Solapur            2670
Tuticorin          2627
Nagpur             2525
Una                2514
Ongole             2504
Ranipet            2446
Khammam            2304
Dharmapuri         2223
Kolar              2102
Thiruvarur         2088
Neemuch            2077
Chhindwara         2027
Jhajjar            2009
Jaipur             1984
Boripardhi         1929
Chengalpattu       1914
Hassan             1864
Surat              1857
Palani             1853
Pollachi           1852
Puducherry         1779
Indore             1766
Nagercoil          1760
Ratlam             1566
Anantapur          1543
Villupuram         1540
Kakinada           1520
Rudrapur           1384
Thiruvallur        1379
Varanasi           1374
Vadodara           1374
Kalaburagi         1364
Shirur             1328
Dindigul           1320
Indapur            1314
Kurnool            1314
Firozabad          1269
Jodhpur            1266
Hubballi           1250
Patna              1165
Hospet             1155
Bikaner            1141
Pinjore            1132
Bhubaneswar        1044
Bilaspur           1023
Aligarh            1020
Erode              1013
Kottakkal          991
Jhansi             966
Namakkal           926
Gwalior            906
Vijayapura         890
Jhunjhunu          886
Kochi              865
Vijayawada         846
Kota               824
Sikar              810
Thirupathi         796
Bhagpat            784
Kolkata            783
Hisar              756
Ahmednagar         746
Dewas              735
Latur              728
Ramnagar           721
Mehsana            719
Nizamabad          718
Meerut             678
Shamli             674
Kalol              671
Buldhana           606
Karur              604
Rohtak             593
Udgir              593
Vapi               586
Satna              575
Sonepat            570
Begusarai          553
Vadali Bhoi        537
Abohar             489
Udaipur            486
Nagda              486
Proddatur          463
Rajsamand          453
Raipur             448
Narnaul            444
Sujangarh          440
Kullu              437
Bhagalpur          434
Vyara              419
Patiala            406
Avadi              402
Chittorgarh        400
Jalpaiguri         388
Paradeep           383
Wai                379
Gangapur           369
Mohania            353
Jharsuguda         313
Bikramganj         296
Kishangarh         279
Barmer             269
Kashipur           256
Shrigonda          256
Jajpur             251
Panchkula          241
Belgaum            232
Chirawa            231
Rosera             230
Chhatarpur         224
Haldwani           213
Kotputli           205
Kottayam           205
Malegaon           200
Ballia             197
Ramanathapuram     197
Reengus            195
Wardha             191
Farrukhbad         186
Kotayyam           183
Rourkela           181
Dhanbad            177
Amritsar           176
Bahr               165
Shahpura           162
Pudukottai         151
Ambikapur          150
Talcher            147
Nadiad             139
Berhampur          130
Gaya               127
Yavatmal           124
Udumalpet          121
Suryapet           106
Alwar              96
Mangaldoi          92
Sangamner          92
Nellore            92
Agra               82
Mughalsarai        79
Amroha             77
Akola              61
Chandigarh         60
Bahraich           59
Guntur             54
Shahjahanpur       44
Rishikesh          43
Muzaffarpur        39
Buxar              28
Rajahmundry        23
Pune-Hinjewadi     20
Bhinmal            19
Kanpur             14
Bazpur             11
Sambalpur          8
Srirampur          5
Tikamgarh          2
Hatras             1
Name: City, dtype: int64

In [166]:
cip2_df["District"].value_counts()

NotAvailable            551689
Maharashtra             128119
Tamil Nadu              116309
Karnataka               44135
Andhra Pradesh          40604
Uttar Pradesh           31534
Gujarat                 24403
Punjab                  22741
Haryana                 17971
Madhya Pradesh          13598
Rajasthan               13466
Telangana               7741
Kerala                  6002
Delhi                   5414
Chandigarh              3319
Himachal Pradesh        3316
Bihar                   3258
Uttarakhand             2541
Odisha                  2305
Puducherry              1716
West Bengal             1332
Dadra and Nagar Hav.    907
Chhattisgarh            622
Daman and Diu           436
Jharkhand               256
Assam                   100
Arunachal Pradesh       62
Goa                     24
Nagaland                24
Jammu and Kashmir       21
Andaman and Nico.In.    8
Lakshadweep             7
Megalaya                7
Sikkim                  6
Tripura                 5
Manipur                 3
Mizoram                 2
Name: District, dtype: int64

In [180]:
state_pop_df = pd.read_excel("../data/AdditionalDatasets/IndiaCityStatesWiki.xlsx", sheet_name='StatePopulation')

In [181]:
state_pop_df

,Rank,District,Population,National Share (%),Decadal growth (2001–2012),Rural population,Percent rural,Urban population,Percent urban,Area,Density,Sex ratio
0,1,Uttar Pradesh,199812341,0.1651,0.202,155317278,0.7773,44495063,0.2227,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,0.0928,0.2,61556074,0.5478,50818259,0.4522,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,0.0860,0.254,92341436,0.8871,11758016,0.1129,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,4,West Bengal,91276115,0.0754,0.138,62183113,0.6813,29093002,0.3187,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,5,Madhya Pradesh,72626809,0.0600,0.163,52557404,0.7237,20069405,0.2763,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
5,6,Tamil Nadu,72147030,0.0596,0.156,37229590,0.5160,34917440,0.4840,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996
6,7,Rajasthan,68548437,0.0566,0.213,51500352,0.7513,17048085,0.2487,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
7,8,Karnataka,61095297,0.0505,0.156,37469335,0.6133,23625962,0.3867,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
8,9,Gujarat,60439692,0.0499,0.193,34694609,0.5740,25745083,0.4260,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
9,10,Andhra Pradesh,"49,577,103[b]",0.0410,0.11,34966693,0.7053,14610410,0.2947,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
10,11,Odisha,41974219,0.0347,0.14,34970562,0.8331,7003656,0.1669,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
11,12,Telangana,35003674,0.0289,0.1358,21395009,0.6112,13608665,0.3888,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
12,13,Kerala,33406061,0.0276,0.049,17471135,0.5230,15934926,0.4770,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
13,14,Jharkhand,32988134,0.0273,0.224,25055073,0.7595,7933061,0.2405,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
14,15,Assam,31205576,0.0258,0.177,26807034,0.8590,4398542,0.1410,"78,438 km2 (30,285 sq mi)","398/km2 (1,030/sq mi)",958
15,16,Punjab,27743338,0.0229,0.1389,17344192,0.6252,10399146,0.3748,"50,362 km2 (19,445 sq mi)","551/km2 (1,430/sq mi)",895
16,17,Chhattisgarh,25545198,0.0211,0.226,19607961,0.7676,5937237,0.2324,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
17,18,Haryana,25351462,0.0209,0.199,16509359,0.6512,8842103,0.3488,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
18,UT1,Delhi,16787941,0.0139,0.212,419042,0.0250,16368899,0.9750,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
19,UT2,Jammu and Kashmir,12267032,0.0101,0.236,9064220,0.7389,3202812,0.2611,"42,241 km2 (16,309 sq mi)[c]",297/km2 (770/sq mi),890
20,19,Uttarakhand,10086292,0.0083,0.188,7036954,0.6977,3049338,0.3023,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
21,20,Himachal Pradesh,6864602,0.0057,0.129,6176050,0.8997,688552,0.1003,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
22,21,Tripura,3673917,0.0030,0.148,2712464,0.7383,961453,0.2617,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
23,22,Meghalaya,2966889,0.0025,0.279,2371439,0.7993,595450,0.2007,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
24,23,Manipur,2570390,0.0021,0.186,1793875,0.6979,776515,0.3021,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
25,24,Nagaland,1978502,0.0016,−0.6%,1407536,0.7114,570966,0.2886,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
26,25,Goa,1458545,0.0012,0.082,551731,0.3783,906814,0.6217,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
27,26,Arunachal Pradesh,1383727,0.0011,0.26,1066358,0.7706,317369,0.2294,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
28,UT3,Puducherry,1247953,0.0010,0.281,395200,0.3167,852753,0.6833,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
29,27,Mizoram,1097206,0.0009,0.235,525435,0.4789,571771,0.5211,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
30,UT4,Chandigarh,1055450,0.0009,0.172,28991,0.0275,1026459,0.9725,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
31,28,Sikkim,610577,0.0005,0.129,456999,0.7485,153578,0.2515,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
32,UT5,Dadra and Nagar Hav.,585764,0.0005,0.551,243510,0.4157,342254,0.5843,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
33,UT5,Daman and Diu,585764,0.0005,0.551,243510,0.4157,342254,0.5843,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
34,UT6,Andaman and Nico.In.,380581,0.0003,0.069,237093,0.6230,143488,0.3770,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
35,UT7,Ladakh,274000,0.0002,0.178,43840,0.1600,230160,0.8400,"96,701 km2 (37,336 sq mi)[e]",2.8/km2 (7.3/sq mi),853
36,UT8,Lakshadweep,64473,0.0001,0.063,14141,0.2193,50332,0.7807,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946
37,Total,India,1210569573,1.0000,0.177,833463448,0.6884,377106125,0.3116,"3,287,240 km2 (1,269,210 sq mi)[f]",382/km2 (990/sq mi),940

In [182]:
#cip3_df = pd.merge(cip2_df,state_pop_df,how='left',left_on='District',right_on='State or union territory')

In [183]:
cip3_df = pd.merge(cip2_df,state_pop_df,how='left',on='District')

In [184]:
cip3_df.isnull().sum()

Business Partner              0
Customer No.                  0
Partner Type                  0
Data Origin                   0
Title                         0
Marital Status                0
Occupation                    0
Date of Birth                 0
Death date                    0
Amt Rcvd From Custom          0
Amt Rcvd From Ins Co          0
Area / Locality               0
CGST(14%)                     0
CGST(2.5%)                    0
CGST(6%)                      0
CGST(9%)                      0
CITY                          0
Cash /Cashless Type           0
Claim No.                     0
Cust Type                     0
District                      0
Expiry Date                   0
Gate Pass Date                0
Gate Pass Time                0
IGST(12%)                     0
IGST(18%)                     0
IGST(28%)                     0
IGST(5%)                      0
Insurance Company             0
Invoice Date                  0
Invoice No                    0
Invoice Time                  0
Job Card No                   0
JobCard Date                  0
JobCard Time                  0
KMs Reading                   0
Labour Total                  0
Make                          0
Misc Total                    0
Model                         0
ODN No.                       0
OSL Total                     0
Order Type                    0
Outstanding Amt               0
Parts Total                   0
Pin code                      0
Plant                         0
Plant Name1                   0
Policy no.                    0
Print Status                  0
Recovrbl Exp                  0
Regn No                       0
SGST/UGST(14%)                0
SGST/UGST(2.5%)               0
SGST/UGST(6%)                 0
SGST/UGST(9%)                 0
Service Advisor Name          0
TDS amount                    0
Technician Name               0
Total Amt Wtd Tax.            0
Total CGST                    0
Total GST                     0
Total IGST                    0
Total SGST/UGST               0
Total Value                   0
User ID                       0
Name 1                        0
Valuation Area                0
Customer no. - plant          0
Vendor number plant           0
Factory calendar              0
Name 2                        0
House number and street       0
PO Box                        0
Postal Code                   0
City                          0
Sales organization            0
State                         0
PriceLow                      0
PriceHigh                     0
Rank                          551696
Population                    551696
National Share (%)            551696
Decadal growth (2001–2012)    551696
Rural population              551696
Percent rural                 551696
Urban population              551696
Percent urban                 551696
Area                          551696
Density                       551696
Sex ratio                     551696
dtype: int64

In [188]:
cip3_df['Rank'].fillna(0, inplace=True)
cip3_df['Population'].fillna(0, inplace=True)
cip3_df['National Share (%)'].fillna(0, inplace=True)
cip3_df['Decadal growth (2001–2012)'].fillna(0, inplace=True)
cip3_df['Rural population'].fillna(0, inplace=True)
cip3_df['Urban population'].fillna(0, inplace=True)
cip3_df['Percent rural'].fillna(0, inplace=True)
cip3_df['Percent urban'].fillna(0, inplace=True)
cip3_df['Area'].fillna(0, inplace=True)
cip3_df['Density'].fillna(0, inplace=True)
cip3_df['Sex ratio'].fillna(0, inplace=True)

In [189]:
cip3_df.isnull().sum()

Business Partner              0
Customer No.                  0
Partner Type                  0
Data Origin                   0
Title                         0
Marital Status                0
Occupation                    0
Date of Birth                 0
Death date                    0
Amt Rcvd From Custom          0
Amt Rcvd From Ins Co          0
Area / Locality               0
CGST(14%)                     0
CGST(2.5%)                    0
CGST(6%)                      0
CGST(9%)                      0
CITY                          0
Cash /Cashless Type           0
Claim No.                     0
Cust Type                     0
District                      0
Expiry Date                   0
Gate Pass Date                0
Gate Pass Time                0
IGST(12%)                     0
IGST(18%)                     0
IGST(28%)                     0
IGST(5%)                      0
Insurance Company             0
Invoice Date                  0
Invoice No                    0
Invoice Time                  0
Job Card No                   0
JobCard Date                  0
JobCard Time                  0
KMs Reading                   0
Labour Total                  0
Make                          0
Misc Total                    0
Model                         0
ODN No.                       0
OSL Total                     0
Order Type                    0
Outstanding Amt               0
Parts Total                   0
Pin code                      0
Plant                         0
Plant Name1                   0
Policy no.                    0
Print Status                  0
Recovrbl Exp                  0
Regn No                       0
SGST/UGST(14%)                0
SGST/UGST(2.5%)               0
SGST/UGST(6%)                 0
SGST/UGST(9%)                 0
Service Advisor Name          0
TDS amount                    0
Technician Name               0
Total Amt Wtd Tax.            0
Total CGST                    0
Total GST                     0
Total IGST                    0
Total SGST/UGST               0
Total Value                   0
User ID                       0
Name 1                        0
Valuation Area                0
Customer no. - plant          0
Vendor number plant           0
Factory calendar              0
Name 2                        0
House number and street       0
PO Box                        0
Postal Code                   0
City                          0
Sales organization            0
State                         0
PriceLow                      0
PriceHigh                     0
Rank                          0
Population                    0
National Share (%)            0
Decadal growth (2001–2012)    0
Rural population              0
Percent rural                 0
Urban population              0
Percent urban                 0
Area                          0
Density                       0
Sex ratio                     0
dtype: int64

In [190]:
cip3_df

,Business Partner,Customer No.,Partner Type,Data Origin,Title,Marital Status,Occupation,Date of Birth,Death date,Amt Rcvd From Custom,Amt Rcvd From Ins Co,Area / Locality,CGST(14%),CGST(2.5%),CGST(6%),CGST(9%),CITY,Cash /Cashless Type,Claim No.,Cust Type,District,Expiry Date,Gate Pass Date,Gate Pass Time,IGST(12%),IGST(18%),IGST(28%),IGST(5%),Insurance Company,Invoice Date,Invoice No,Invoice Time,Job Card No,JobCard Date,JobCard Time,KMs Reading,Labour Total,Make,Misc Total,Model,ODN No.,OSL Total,Order Type,Outstanding Amt,Parts Total,Pin code,Plant,Plant Name1,Policy no.,Print Status,Recovrbl Exp,Regn No,SGST/UGST(14%),SGST/UGST(2.5%),SGST/UGST(6%),SGST/UGST(9%),Service Advisor Name,TDS amount,Technician Name,Total Amt Wtd Tax.,Total CGST,Total GST,Total IGST,Total SGST/UGST,Total Value,User ID,Name 1,Valuation Area,Customer no. - plant,Vendor number plant,Factory calendar,Name 2,House number and street,PO Box,Postal Code,City,Sales organization,State,PriceLow,PriceHigh,Rank,Population,National Share (%),Decadal growth (2001–2012),Rural population,Percent rural,Urban population,Percent urban,Area,Density,Sex ratio
0,31,1,1.0,Z001,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,0.00,0.00,0,0,0.0000,0,0.0,0.000,0.0,0.000,0,0,0.0
1,32,2,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,0.00,0.00,0,0,0.0000,0,0.0,0.000,0.0,0.000,0,0,0.0
2,34,4,1.0,Z005,0.0,2.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,0.00,0.00,0,0,0.0000,0,0.0,0.000,0.0,0.000,0,0,0.0
3,35,5,1.0,Z005,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,0.00,0.00,0,0,0.0000,0,0.0,0.000,0.0,0.000,0,0,0.0
4,42,7,1.0,Z008,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,NotAvailable,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,01-01-1900,0.000000e+00,00:00:00,0.0,01-01-1900,00:00:00,0.0,0.00,NotAvailable,0.00,NotAvailable,0,0.0,NotAvailable,0.0,0.00,0.0,NotAvailable,NotAvailable,NotAvailable,NotAvailable,0.0,NotAvailable,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,0.00,0.0,0.0,0.0,0.0,0.0,NotAvailable,NotAvailable,Not Available,Not Available,Not Available,IN,Not Available,Not Available,0.0,0.0,Not Available,Not Available,Not Available,0.00,0.00,0,0,0.0000,0,0.0,0.000,0.0,0.000,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043998,NotAvailable,203817,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,"THANDURAI,",0.0,0.0,0.0,0.0,Pattabiram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,13:35:31,400080.0,2016-06-30,08:33:22,32173.0,774.03,MARUTI SUZUKI,0.00,SWIFT,0,0.0,Paid Service,0.0,1030.40,600072.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN12K5923,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,1804.43,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,5.73,8.41,6,72147030,0.0596,0.156,37229590.0,0.516,34917440.0,0.484,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996.0
1043999,NotAvailable,203808,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,KONNUR HIGH ROAD,0.0,0.0,0.0,0.0,ayanavaram,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:05:30,400074.0,2016-06-30,08:03:18,15905.0,1346.90,MARUTI SUZUKI,0.00,RITZ,0,0.0,Paid Service,0.0,882.17,600085.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN01AT3623,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,2229.07,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,4.45,6.81,6,72147030,0.0596,0.156,37229590.0,0.516,34917440.0,0.484,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996.0
1044000,NotAvailable,203844,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,CHENNAI,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:30:23,400150.0,2016-06-30,09:58:59,100165.0,5063.08,MAHINDRA & MAHINDRA,0.00,XYLO,0,0.0,Paid Service,0.0,6989.06,600109.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN22BW1485,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,12052.14,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,8.86,12.13,6,72147030,0.0596,0.156,37229590.0,0.516,34917440.0,0.484,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996.0
1044001,NotAvailable,203820,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,.,0.0,0.0,0.0,0.0,Chennai,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,14:56:58,400100.0,2016-06-30,09:15:12,72546.0,2495.90,MARUTI SUZUKI,374.97,ALTO,0,0.0,Paid Service,0.0,1587.28,600058.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN38Y9343,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,4458.15,0.0,0.0,0.0,0.0,0.0,X405SA1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,2.99,4.60,6,72147030,0.0596,0.156,37229590.0,0.516,34917440.0,0.484,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996.0
1044002,NotAvailable,204288,0.0,0,0.0,0.0,0.0,01-01-1900,31-12-3000,0.0,0.0,2ND FLOOR,0.0,0.0,0.0,0.0,saidapet,NotAvailable,NotAvailable,Retail,Tamil Nadu,31-12-3000,31-12-3000,00:00:00,0.0,0.0,0.0,0.0,NotAvailable,2016-06-30,7.231000e+09,17:09:19,400891.0,2016-06-30,16:54:06,149197.0,747.78,MARUTI SUZUKI,0.00,WAGONR,0,0.0,Running Repairs,0.0,0.00,600016.0,X405,X405 - NANGAN MOTORS PVT. LTD.,NotAvailable,NO,0.0,TN10T3317,0.0,0.0,0.0,0.0,NotAvailable,0.0,NotAvailable,747.78,0.0,0.0,0.0,0.0,0.0,X405WM1,X405 - NANGAN MOTORS PVT. LTD.,X405,PLX405,NotAvailable,IN,Chennai,"Block No 6, Thiru Vi Ka Indust",600032.0,600032.0,Chennai,MFCA,Tamil Nadu,4.79,6.32,6,72147030,0.0596,0.156,37229590.0,0.516,34917440.0,0.484,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996.0

In [191]:
cip3_df.to_csv("../data/cip3.csv")